/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-12-15 08:57:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Info;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class gradeBenefit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/milkyWayForest/css/grade.css\">\r\n");
      out.write("</head> \r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".bg-white {\r\n");
      out.write("	padding-top : 50px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<form id=\"gradeBenefitForm\" name=\"gradeBenefitForm\">\r\n");
      out.write("	<div id=\"container\">\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"grade_text1\">\r\n");
      out.write("				<div class=\"grade-top-text\"><h1>등급 및 혜택</h1></div>\r\n");
      out.write("					\r\n");
      out.write("			<div id=\"top_text\">\r\n");
      out.write("				<div>\r\n");
      out.write("					<a href=\"/milkyWayForest/\"><img src=\"/milkyWayForest/image/icon_home.png\" alt=\"홈\"></a> > \r\n");
      out.write("					<a href=\"/milkyWayForest/info/gradeBenefitInfo\">EunhaSoop Rewards</a> > \r\n");
      out.write("					<a href=\"/milkyWayForest/info/gradeBenefitInfo\">은하숲 리워드</a> >\r\n");
      out.write("					<a href=\"/milkyWayForest/info/gradeBenefitInfo\" style=\"font-weight:bold;\">등급 및 혜택</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"grade_pic1\">\r\n");
      out.write("		<img src=\"/milkyWayForest/image/benefit.png\" alt=\"benefit\" width=\"100%\" >\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<h3 class=\"grade_text2\"><strong>회원 등급별 혜택</strong></h3>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"second_block\">\r\n");
      out.write("	\r\n");
      out.write("		<div class=\"one\">\r\n");
      out.write("			<img src=\"/milkyWayForest/image/welcome.png\" alt=\"welcome\" width=\"100%\">\r\n");
      out.write("			<pre class=\"welcome_text\" \r\n");
      out.write("			style=\"margin-bottom: 12px; font-size: 18px; \r\n");
      out.write("			color: #666; line-height: 2; padding-left: 13px;\">\r\n");
      out.write("			</pre>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"two\">\r\n");
      out.write("			<img src=\"/milkyWayForest/image/green.PNG\" alt=\"welcome\" width=\"100%\">\r\n");
      out.write("			<pre class=\"green_text\" \r\n");
      out.write("			style=\"margin-bottom: 12px; font-size: 18px; \r\n");
      out.write("			color: #666; line-height: 2; padding-left: 13px;\">\r\n");
      out.write("			</pre>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"three\">\r\n");
      out.write("			<img src=\"/milkyWayForest/image/gold.PNG\" alt=\"welcome\" width=\"100%\">\r\n");
      out.write("			<pre class=\"gold_text\" \r\n");
      out.write("			style=\"margin-bottom: 12px; font-size: 18px; \r\n");
      out.write("			color: #666; line-height: 2; padding-left: 13px;\" >\r\n");
      out.write("			</pre>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<ul class=\"info1_text\">		\r\n");
      out.write("		<li class=\"list\">My DT Pass 서비스 이용 : 차량번호를 사전에 등록하시면, DT 매장에서 주문 후 결제 단계 없이 상품을 빠르게 수령하실 수 있습니다.</li>\r\n");
      out.write("		<li class=\"list\">Welcome Level이 바로 적용됩니다. Welcome Level이 되신 후, 적립금 1000원을 받으실 수 있어요!</li>\r\n");
      out.write("		<li class=\"list\">영수증 쿠폰을 e-쿠폰으로 발행 받거나 모바일 APP/WEB에 등록하여 사용하실 수 있습니다.</li>\r\n");
      out.write("		<li class=\"list\">Green / Gold Level은 해당 등급조건을 충족한 다음 날부터 적용됩니다.</li>\r\n");
      out.write("		<li class=\"list\">별★의 유효기간은 일년입니다.</li>\r\n");
      out.write("		<li class=\"list\">쿠폰 및 그린/골드 대상 회원 전용 이벤트는 프로모션 운영에 따라 변경될 수 있습니다.</li>\r\n");
      out.write("	</ul>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("	<div id=\"container2\">\r\n");
      out.write("	<section class=\"info2\">\r\n");
      out.write("		<article class=\"info2_inner\" id=\"showcase\">\r\n");
      out.write("			<div class=\"info2_center\">\r\n");
      out.write("			<h3><strong>회원 등급별 상세 혜택 및 유의사항</strong></h3>\r\n");
      out.write("			\r\n");
      out.write("			<!-- 카드 -->\r\n");
      out.write("			<div id=\"cardList_wrap\">\r\n");
      out.write("				<div id=\"cardList\">\r\n");
      out.write("				\r\n");
      out.write("					<!--  버튼1 -->\r\n");
      out.write("					<div id=\"1\" class=\"item bg-white\" style=\"op\">\r\n");
      out.write("						<div class=\"1_1pic\" align=\"center\" style=\"padding-top:2.5rem;\">\r\n");
      out.write("							<img src=\"/milkyWayForest/image/list_01_bg.png\" alt=\"list_01\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"1_2pic\" align=\"center\">\r\n");
      out.write("							<img src=\"/milkyWayForest/image/icon_level_03.png\" alt=\"list_01\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<p class=\"1_text\" align=\"center\" style=\"padding-top:1rem;\">\r\n");
      out.write("							골드회원 적립금 5%\r\n");
      out.write("						</p>\r\n");
      out.write("						<div align=\"center\" style=\"padding-top:1rem;\">\r\n");
      out.write("							<!-- <button type=\"button\" class=\"btn btn-outline-secondary\" id=\"button1_open\" data-toggle=\"modal\" data-target=\"#modal1\">자세히 보기</button> -->\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("	\r\n");
      out.write("					\r\n");
      out.write("					<div id=\"2\" class=\"item bg-white\">\r\n");
      out.write("						<div class=\"2_1pic\" align=\"center\" style=\"padding-top:3.5rem;\">\r\n");
      out.write("							<img src=\"/milkyWayForest/image/list_02_bg.png\" alt=\"list_01\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"2_2pic\" align=\"center\" style=\"padding-top:.5rem;\" >\r\n");
      out.write("							<img src=\"/milkyWayForest/image/icon_level_03.png\" alt=\"list_01\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<p class=\"2_text\" align=\"center\" style=\"padding-top:.8rem;\">\r\n");
      out.write("							Personalized Offer 쿠폰\r\n");
      out.write("						</p>\r\n");
      out.write("						<div align=\"center\" style=\"padding-top:1rem;\">\r\n");
      out.write("							<!-- <button type=\"button\" class=\"btn btn-outline-secondary\">자세히 보기</button> -->\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					<div id=\"3\" class=\"item bg-white\">\r\n");
      out.write("						<div class=\"3_1pic\" align=\"center\" style=\"padding-top:1.9rem;\">\r\n");
      out.write("							<img src=\"/milkyWayForest/image/list_03_gold_bg.png\" alt=\"list_01\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"3_2pic\" align=\"center\">\r\n");
      out.write("							<img src=\"/milkyWayForest/image/icon_level_03.png\" alt=\"list_01\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<p class=\"3_text\" align=\"center\" style=\"padding-top:1rem;\">\r\n");
      out.write("							골드회원만의 e-Gold Card 발급!\r\n");
      out.write("						</p>\r\n");
      out.write("						<div align=\"center\" style=\"padding-top:1rem;\">\r\n");
      out.write("							<!-- <button type=\"button\" class=\"btn btn-outline-secondary\">자세히 보기</button> -->\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					<div id=\"4\" class=\"item bg-white\">\r\n");
      out.write("						<div class=\"4_1pic\" align=\"center\" style=\"padding-top:3rem;\">\r\n");
      out.write("							<img src=\"/milkyWayForest/image/web_msr_icon_02.png\" alt=\"list_01\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"4_2pic\" align=\"center\">\r\n");
      out.write("							<img src=\"/milkyWayForest/image/icon_level_03.png\" alt=\"list_01\">\r\n");
      out.write("							<img src=\"/milkyWayForest/image/icon_level_02.png\" alt=\"list_01\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<p class=\"4_text\" align=\"center\" style=\"padding-top:1rem;\">\r\n");
      out.write("							Beverage BOGO 쿠폰\r\n");
      out.write("						</p>\r\n");
      out.write("						<div align=\"center\" style=\"padding-top:1rem;\">\r\n");
      out.write("							<!-- <button type=\"button\" class=\"btn btn-outline-secondary\">자세히 보기</button> -->\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					<div id=\"5\" class=\"item bg-white\">\r\n");
      out.write("						<div class=\"5_1pic\" align=\"center\" style=\"padding-top:3rem;\">\r\n");
      out.write("							<img src=\"/milkyWayForest/image/list_13_bg.png\" alt=\"list_01\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"5_2pic\" align=\"center\">\r\n");
      out.write("							<img src=\"/milkyWayForest/image/icon_level_03.png\" alt=\"list_01\">\r\n");
      out.write("							<img src=\"/milkyWayForest/image/icon_level_02.png\" alt=\"list_01\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<p class=\"5_text\" align=\"center\" style=\"padding-top:1rem;\">\r\n");
      out.write("							250g 원두 또는 12개입 VIA 구매 시,<br>\r\n");
      out.write("							카페 아메리카노(Hot/Iced) 쿠폰\r\n");
      out.write("						</p>\r\n");
      out.write("						<div align=\"center\" style=\"padding-top:1rem;\">\r\n");
      out.write("							<!-- <button type=\"button\" class=\"btn btn-outline-secondary\">자세히 보기</button> -->\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					<div id=\"6\" class=\"item bg-white\">\r\n");
      out.write("						<div class=\"6_1pic\" align=\"center\" style=\"padding-top:2rem;\">\r\n");
      out.write("							<img src=\"/milkyWayForest/image/list_06_bg.png\" alt=\"list_01\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"6_2pic\" align=\"center\" style=\"padding-top:.5rem;\">\r\n");
      out.write("							<img src=\"/milkyWayForest/image/icon_level_03.png\" alt=\"list_01\">\r\n");
      out.write("							<img src=\"/milkyWayForest/image/icon_level_02.png\" alt=\"list_01\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<p class=\"6_text\" align=\"center\" style=\"padding-top:1rem;\">\r\n");
      out.write("							스타벅스 리저브™ 원두 구매 시,<br> \r\n");
      out.write("							스타벅스 리저브™ 음료\r\n");
      out.write("						</p>\r\n");
      out.write("						<div align=\"center\" style=\"padding-top:.5rem;\">\r\n");
      out.write("							<!-- <button type=\"button\" class=\"btn btn-outline-secondary\">자세히 보기</button> -->\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					<div id=\"7\" class=\"item bg-white\">\r\n");
      out.write("						<div class=\"7_1pic\" align=\"center\" style=\"padding-top:2rem;\">\r\n");
      out.write("							<img src=\"/milkyWayForest/image/tevana_Icon.png\" alt=\"list_01\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"7_2pic\" align=\"center\" style=\"padding-top:.5rem;\">\r\n");
      out.write("							<img src=\"/milkyWayForest/image/icon_level_03.png\" alt=\"list_01\">\r\n");
      out.write("							<img src=\"/milkyWayForest/image/icon_level_02.png\" alt=\"list_01\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<p class=\"7_text\" align=\"center\" style=\"padding-top:1rem;\">\r\n");
      out.write("							티바나 패키지 티 구매 시,<br>\r\n");
      out.write("							풀 리프 티(Hot/Iced) 쿠폰\r\n");
      out.write("						</p>\r\n");
      out.write("						<div align=\"center\" style=\"padding-top:.5rem;\">\r\n");
      out.write("							<!-- <button type=\"button\" class=\"btn btn-outline-secondary\">자세히 보기</button> -->\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					<div id=\"8\" class=\"item bg-white\">\r\n");
      out.write("						<div class=\"8_1pic\" align=\"center\" style=\"padding-top:2rem;\">\r\n");
      out.write("							<img src=\"/milkyWayForest/image/web_msr_icon_03.png\" alt=\"list_01\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"8_2pic\" align=\"center\" style=\"padding-top:.5rem;\">\r\n");
      out.write("							<img src=\"/milkyWayForest/image/icon_level_03.png\" alt=\"list_01\">\r\n");
      out.write("							<img src=\"/milkyWayForest/image/icon_level_02.png\" alt=\"list_01\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<p class=\"8_text\" align=\"center\" style=\"padding-top:2rem;\">\r\n");
      out.write("							생일 쿠폰 발행\r\n");
      out.write("						</p>\r\n");
      out.write("						<div align=\"center\" style=\"padding-top:.8rem;\">\r\n");
      out.write("							<!-- <button type=\"button\" class=\"btn btn-outline-secondary\">자세히 보기</button> -->\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					<div id=\"9\" class=\"item bg-white\">\r\n");
      out.write("						<div class=\"9_1pic\" align=\"center\" style=\"padding-top:2rem;\">\r\n");
      out.write("							<img src=\"/milkyWayForest/image/web_msr_icon_01.png\" alt=\"list_01\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"9_2pic\" align=\"center\" style=\"padding-top:.5rem;\">\r\n");
      out.write("							<img src=\"/milkyWayForest/image/icon_level_03.png\" alt=\"list_01\">\r\n");
      out.write("							<img src=\"/milkyWayForest/image/icon_level_02.png\" alt=\"list_01\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<p class=\"9_text\" align=\"center\" style=\"padding-top:2rem;\">\r\n");
      out.write("							웰컴 첫 구매 쿠폰 발행\r\n");
      out.write("						</p>\r\n");
      out.write("						<div align=\"center\" style=\"padding-top:.8rem;\">\r\n");
      out.write("						<!-- 	<button type=\"button\" class=\"btn btn-outline-secondary\">자세히 보기</button> -->\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					<div id=\"10\" class=\"item bg-white\">\r\n");
      out.write("						<div class=\"10_1pic\" align=\"center\" style=\"padding-top:3.5rem;\">\r\n");
      out.write("							<img src=\"/milkyWayForest/image/list_08_bg.png\" alt=\"list_01\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"10_2pic\" align=\"center\" style=\"padding-top:.5rem;\">\r\n");
      out.write("							<img src=\"/milkyWayForest/image/icon_level_03.png\" alt=\"list_01\">\r\n");
      out.write("							<img src=\"/milkyWayForest/image/icon_level_02.png\" alt=\"list_01\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<p class=\"10_text\" align=\"center\" style=\"padding-top:2rem;\">\r\n");
      out.write("							분실 신고 시 잔액 보호\r\n");
      out.write("						</p>\r\n");
      out.write("						<div align=\"center\" style=\"padding-top:.8rem;\">\r\n");
      out.write("							<!-- <button type=\"button\" class=\"btn btn-outline-secondary\" \r\n");
      out.write("							data-toggle=\"modal\" data-target=\"#exampleModal\">\r\n");
      out.write("								자세히 보기\r\n");
      out.write("							</button> -->\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					<div id=\"11\" class=\"item bg-white\">\r\n");
      out.write("						<div class=\"11_1pic\" align=\"center\" style=\"padding-top:2.5rem;\">\r\n");
      out.write("							<img src=\"/milkyWayForest/image/web_msr_icon_04.png\" alt=\"list_01\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"11_2pic\" align=\"center\" style=\"padding-top:1rem;\">\r\n");
      out.write("							<img src=\"/milkyWayForest/image/icon_level_03.png\" alt=\"list_01\">\r\n");
      out.write("							<img src=\"/milkyWayForest/image/icon_level_02.png\" alt=\"list_01\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<p class=\"11_text\" align=\"center\" style=\"padding-top:1.5rem;\">\r\n");
      out.write("							스타벅스 카드로 구매 시,<br>\r\n");
      out.write("							Free Extra 1개 제공\r\n");
      out.write("						</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					<div id=\"12\" class=\"item bg-white\">\r\n");
      out.write("						<div class=\"12_1pic\" align=\"center\" style=\"padding-top:2.5rem;\">\r\n");
      out.write("							<img src=\"/milkyWayForest/image/list_10_bg.png\" alt=\"list_01\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"12_2pic\" align=\"center\" style=\"padding-top:1rem;\">\r\n");
      out.write("							<img src=\"/milkyWayForest/image/icon_level_03.png\" alt=\"list_01\">\r\n");
      out.write("							<img src=\"/milkyWayForest/image/icon_level_02.png\" alt=\"list_01\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<p class=\"12_text\" align=\"center\" style=\"padding-top:1.5rem;\">\r\n");
      out.write("							기능 설정 후 스타벅스<br> \r\n");
      out.write("							카드로 결제 시, 현금영수증<br> \r\n");
      out.write("							자동 발행\r\n");
      out.write("						</p>\r\n");
      out.write("					</div>	\r\n");
      out.write("				</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</article>\r\n");
      out.write("	</section>\r\n");
      out.write("	</div>\r\n");
      out.write("</form>\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function(){\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url: '/milkyWayForest/info/getBenefit',  \r\n");
      out.write("		type: 'post',\r\n");
      out.write("		//dataType: 'json',\r\n");
      out.write("		success : function(data) {\r\n");
      out.write("			\r\n");
      out.write("			/* alert(JSON.stringify(data)); */\r\n");
      out.write("			$.each(data, function(index,items) {\r\n");
      out.write("				if(items.gradeName=='welcome'){\r\n");
      out.write("					$('.welcome_text').text(items.gradeBenefit)\r\n");
      out.write("				}else if(items.gradeName=='green'){\r\n");
      out.write("					$('.green_text').text(items.gradeBenefit)\r\n");
      out.write("				}else if(items.gradeName=='gold'){\r\n");
      out.write("					$('.gold_text').text(items.gradeBenefit)\r\n");
      out.write("				}\r\n");
      out.write("			});	\r\n");
      out.write("		},\r\n");
      out.write("		error: function(err) {\r\n");
      out.write("			console.log(err);\r\n");
      out.write("		}\r\n");
      out.write("	});	\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</body> \r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
