/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-12-15 01:33:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class pAllMenu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#menuContainer {\r\n");
      out.write("	display: flex;\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("#menuContainer #mainNavMenu, #menuContainer #subNavMenu, #menuContainer #subNavMenu2  {\r\n");
      out.write("	width: 50%;\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("#menuContainer li:first-child {\r\n");
      out.write("	font-size: 15pt;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	margin : 5px;\r\n");
      out.write("	list-style: none;\r\n");
      out.write("	text-indent: -10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#menuContainer li {\r\n");
      out.write("	list-style: none;\r\n");
      out.write("	font-size: 10pt;\r\n");
      out.write("	color: #154520;\r\n");
      out.write("	opacity:1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#menuContainer a:link { \r\n");
      out.write("\r\n");
      out.write("color: #154520; text-decoration: none; \r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#menuContainer a:visited { \r\n");
      out.write("\r\n");
      out.write("color: #154520; text-decoration: none; \r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#menuContainer a:hover { \r\n");
      out.write("color: black; \r\n");
      out.write("text-shadow:-1px 0 	#FFC81E, 0 1px 	#FFC81E, 1px 0 	#FFC81E,  0 -1px #FFC81E;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#menuContainer a:active { \r\n");
      out.write("\r\n");
      out.write("color: #154520; text-decoration: none; \r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#menuContainer li a {\r\n");
      out.write("	color: 	#154520;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".card .card-body {\r\n");
      out.write("	background :url(\"/milkyWayForest/image/pBackPhoto3.jpg\")\r\n");
      out.write("	no-repeat center;\r\n");
      out.write("	height: 100vh;\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<div class=\"card\">\r\n");
      out.write("	<div class=\"card-body\">\r\n");
      out.write("		<div id=\"menuContainer\">\r\n");
      out.write("			<div id=\"mainNavMenu\">\r\n");
      out.write("				<ul id=\"main\">\r\n");
      out.write("					<li><a href=\"/milkyWayForest/\">메인페이지</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("				<ul id=\"companyInfo\">\r\n");
      out.write("					<li><a href=\"/milkyWayForest/info/componyInfo\">회사소개</a></li>\r\n");
      out.write("					\r\n");
      out.write("					<li><a href=\"/milkyWayForest/info/componyInfo\">회사소개</a></li>\r\n");
      out.write("					<li><a href=\"/milkyWayForest/info/gradeBenefitInfo\">등급 혜택 안내</a></li>\r\n");
      out.write("				</ul><!-- 회사소개 -->\r\n");
      out.write("			\r\n");
      out.write("				<ul id=\"menuInfo\">\r\n");
      out.write("					<li><a href=\"/milkyWayForest/menuInfo\">메뉴소개</a></li>\r\n");
      out.write("					\r\n");
      out.write("					<li><a href=\"/milkyWayForest/menuInfo/drinkInfo\">음료</a></li>\r\n");
      out.write("					<li><a href=\"/milkyWayForest/menuInfo/menuInfo?category=차&menuCode=T&pg=1\">차</a></li>\r\n");
      out.write("					<li><a href=\"/milkyWayForest/menuInfo/menuInfo?category=커피&menuCode=C&pg=1\">커피</a></li>\r\n");
      out.write("					\r\n");
      out.write("					<li><a href=\"/milkyWayForest/menuInfo/foodInfo\">푸드</a></li>\r\n");
      out.write("					<li><a href=\"/milkyWayForest/menuInfo/menuInfo?category=케이크&menuCode=K&pg=1\">케이크</a></li>\r\n");
      out.write("					<li><a href=\"/milkyWayForest/menuInfo/menuInfo?category=브레드&menuCode=B&pg=1\">브레드</a></li>\r\n");
      out.write("					<li><a href=\"/milkyWayForest/menuInfo/menuInfo?category=샐러드&menuCode=D&pg=1\">샐러드</a></li>\r\n");
      out.write("					<li><a href=\"/milkyWayForest/menuInfo/menuInfo?category=샌드위치&menuCode=S&pg=1\">샌드위치</a></li>	\r\n");
      out.write("					\r\n");
      out.write("					<li><a href=\"/milkyWayForest/menuInfo/menuDetail\">메뉴소개 상세 페이지</a></li>\r\n");
      out.write("				</ul><!-- 메뉴소개 -->\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				<ul id=\"findStore\">\r\n");
      out.write("					<li><a href=\"/milkyWayForest/findStore\">매장찾기</a></li>\r\n");
      out.write("				</ul><!-- 매장찾기 -->\r\n");
      out.write("				\r\n");
      out.write("				<ul id=\"notice\">\r\n");
      out.write("					<li><a href=\"/milkyWayForest/notice/noticeBoard?pg=1\">공지사항</a></li>\r\n");
      out.write("					\r\n");
      out.write("					<li><a href=\"/milkyWayForest/notice/noticeBoard?pg=1\">공지사항</a></li>\r\n");
      out.write("					<li><a href=\"/milkyWayForest/notice/eventBoard\">이벤트</a></li>\r\n");
      out.write("					<li><a href=\"/milkyWayForest/notice/faqBoard?pg=1\">자주 묻는 질문</a></li>\r\n");
      out.write("					<li><a href=\"/milkyWayForest/notice/qnaBoard?pg=1\">문의 게시판</a></li>\r\n");
      out.write("					\r\n");
      out.write("					<li><a href=\"/milkyWayForest/notice/eventView?eventCode=001\">이벤트 글내용</a></li>\r\n");
      out.write("				</ul><!-- 공지사항 -->\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			</div>  <!-- mainNavMenu -->\r\n");
      out.write("			\r\n");
      out.write("			<!-- 서브 Nav2 -->\r\n");
      out.write("			<div id=\"subNavMenu2\">\r\n");
      out.write("				<ul id=\"shopping\">\r\n");
      out.write("					<li><a href=\"/milkyWayForest/shopping\">쇼핑</a></li>\r\n");
      out.write("					\r\n");
      out.write("					<li><a href=\"/milkyWayForest/shopping/beanNTea\">원두/차</a></li>\r\n");
      out.write("					<li><a href=\"/milkyWayForest/shopping/beanList\">원두</a></li>\r\n");
      out.write("					<li><a href=\"/milkyWayForest/shopping/teaList\">차</a></li>\r\n");
      out.write("					\r\n");
      out.write("					<li><a href=\"/milkyWayForest/shopping/product\">상품</a></li>\r\n");
      out.write("					<li><a href=\"/milkyWayForest/shopping/mugList\">머그</a></li>\r\n");
      out.write("					<li><a href=\"/milkyWayForest/shopping/glassList\">글라스</a></li>\r\n");
      out.write("					<li><a href=\"/milkyWayForest/shopping/plasticTumblrList\">플라스틱 텀블러</a></li>\r\n");
      out.write("					<li><a href=\"/milkyWayForest/shopping/stainlessTumblrList\">스테인리스 텀블러</a></li>\r\n");
      out.write("					<li><a href=\"/milkyWayForest/shopping/thermosList\">보온병</a></li>\r\n");
      out.write("					<li><a href=\"/milkyWayForest/shopping/coffeeEtcList\">커피 용품</a></li>\r\n");
      out.write("					\r\n");
      out.write("					<li><a href=\"/milkyWayForest/shopping/shoppingDetail\">쇼핑 상세 페이지</a></li>\r\n");
      out.write("				</ul><!-- 쇼핑 -->\r\n");
      out.write("				\r\n");
      out.write("				<ul id=\"myPage\">\r\n");
      out.write("					<li><a href=\"/milkyWayForest/mypage/mypageMain\">마이페이지</a></li>\r\n");
      out.write("					\r\n");
      out.write("					<li><a href=\"\">주문/배송정보</a></li>\r\n");
      out.write("					<li><a href=\"\">주문 내역</a></li>\r\n");
      out.write("					<li><a href=\"\">주문 현황</a></li>\r\n");
      out.write("					\r\n");
      out.write("					<li><a href=\"\">나의 활동</a></li>\r\n");
      out.write("					<li><a href=\"\">등급/혜택</a></li>\r\n");
      out.write("					<li><a href=\"\">적립금/쿠폰</a></li>\r\n");
      out.write("					<li><a href=\"\">찜관리</a></li>\r\n");
      out.write("					<li><a href=\"/milkyWayForest/mypage/mypageMyPost?pg=1\">게시글 관리</a></li>\r\n");
      out.write("					\r\n");
      out.write("					<li><a href=\"/milkyWayForest/mypage/mypageMyInfo\">개인정보</a></li>\r\n");
      out.write("					<li><a href=\"/milkyWayForest/mypage/mypageMyInfoUpdate\">정보수정</a></li>\r\n");
      out.write("					<li><a href=\"\">배송지 관리</a></li>\r\n");
      out.write("					<li><a href=\"/milkyWayForest/mypage/mypageMyInfoDelete\">탈퇴</a></li>\r\n");
      out.write("				</ul><!-- 마이 페이지 -->\r\n");
      out.write("				\r\n");
      out.write("			\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			<!-- 서브 Nav -->\r\n");
      out.write("			<div id=\"subNavMenu\">\r\n");
      out.write("				<ul id=\"memberWrite\">\r\n");
      out.write("					<li><a href=\"/milkyWayForest/write/memberWrite\">회원가입</a></li>\r\n");
      out.write("					<li><a href=\"/milkyWayForest/write/memberAgree\">약관동의</a></li>\r\n");
      out.write("					<li><a href=\"/milkyWayForest/write/writeIdCheck\">아이디 중복체크</a></li>\r\n");
      out.write("					<li><a href=\"/milkyWayForest/write/writeEmailCheck\">이메일 인증</a></li>\r\n");
      out.write("					<li><a href=\"/milkyWayForest/write/writeOk\">회원가입 완료</a></li>\r\n");
      out.write("					<li><a href=\"\">간편 회원 가입</a></li>\r\n");
      out.write("				</ul><!-- 회원가입 -->\r\n");
      out.write("				\r\n");
      out.write("				<ul id=\"memberLogin\">\r\n");
      out.write("					<li><a href=\"/milkyWayForest/login/loginForm\">로그인</a></li>\r\n");
      out.write("					<li><a href=\"/milkyWayForest/login/findId\">아이디 찾기</a></li>\r\n");
      out.write("					<li><a href=\"/milkyWayForest/login/findPwd\">비밀번호 찾기</a></li>\r\n");
      out.write("				</ul><!-- 로그인 -->\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("								\r\n");
      out.write("				<ul id=\"cart\">\r\n");
      out.write("					<li><a href=\"/milkyWayForest/cart\">장바구니</a></li>\r\n");
      out.write("					<li><a href=\"\">수량버튼</a></li>\r\n");
      out.write("					<li><a href=\"\">선택주문</a></li>\r\n");
      out.write("					<li><a href=\"\">선택삭제</a></li>\r\n");
      out.write("					<li><a href=\"\">전체주문</a></li>\r\n");
      out.write("					<li><a href=\"\">전체삭제</a></li>\r\n");
      out.write("				</ul><!-- 장바구니 -->\r\n");
      out.write("				\r\n");
      out.write("				<ul id=\"pay\">\r\n");
      out.write("					<li><a href=\"/milkyWayForest/payment\">결제페이지</a></li>\r\n");
      out.write("					<li><a href=\"\">결제진행중</a></li>\r\n");
      out.write("					<li><a href=\"\">결제완료</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div> <!-- subNavMenu  -->\r\n");
      out.write("		</div> <!-- menuContainer  -->\r\n");
      out.write("	</div> <!-- card-body -->\r\n");
      out.write("</div> <!-- card -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
