/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-12-15 07:32:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.shopping;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class shoppingDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1639138034579L));
    _jspx_dependants.put("jar:file:/D:/Spring/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/milkyWayForest/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/milkyWayForest/bootstrap/css/bootstrap.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/milkyWayForest/css/shopping.css\">\r\n");
      out.write("\r\n");
      out.write("<form id=\"shoppingDetailForm\" name=\"shoppingDetailForm\">\r\n");
      out.write("	<input type =\"hidden\" name=\"productCode\" id=\"productCode\" value =\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productCode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("	\r\n");
      out.write("	<section id=\"content_box\">\r\n");
      out.write("		<h1>상품</h1>\r\n");
      out.write("		\r\n");
      out.write("		<div id=\"shoppingDetailNav\">\r\n");
      out.write("			<div id=\"shoppingDetailCategory\">\r\n");
      out.write("				<a href=\"/milkyWayForest/\"><img src=\"/milkyWayForest/image/icon_home.png\" alt=\"홈\"></a> > \r\n");
      out.write("				<a href=\"/milkyWayForest/shopping\">Shopping</a> > \r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"productView\">\r\n");
      out.write("		<input type=\"hidden\" id=\"categoryDiv\">\r\n");
      out.write("		<div class=\"shoppingDetailImg items\">\r\n");
      out.write("			<div id=\"shoppingDetailBigImg\">\r\n");
      out.write("				<img alt=\"B001\" id=\"bigImg\" class=\"imgClick\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<ul class=\"imgList\">\r\n");
      out.write("				<li class=\"on\">\r\n");
      out.write("					<div class=\"imgListBorder\">\r\n");
      out.write("					<a href=\"#a\">\r\n");
      out.write("					<img id=\"img1\" alt=\"B001\">\r\n");
      out.write("					</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</li>\r\n");
      out.write("				<!-- 에이작스에서 li 추가해주기 사진이 있을때만 추가하는걸로 바꿔줌! -->\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<!-- 테이블로 상품이름 및 용량 가격 옵션 등 넣기  -->\r\n");
      out.write("		<div id=\"detailTableDiv\" class=\"items\">\r\n");
      out.write("			<table id=\"detailTable\">\r\n");
      out.write("			\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td id=\"productKorName\" colspan=\"2\" style=\"padding-top: 0;\">\r\n");
      out.write("						<span id=\"korsubjectSpan\"></span>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td id=\"productEngName\" colspan=\"2\">\r\n");
      out.write("						<span id=\"engsubjectSpan\"></span>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td colspan=\"2\" style=\"padding: 20px 0;\">\r\n");
      out.write("						<span id=\"productSmallinfoSpan\"></span>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>가격</td>\r\n");
      out.write("					<td class=\"price\">\r\n");
      out.write("						<b><span id=\"productpriceSpan\"></span></b>원\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>옵션</td>\r\n");
      out.write("					<td>\r\n");
      out.write("						\r\n");
      out.write("						<select class=\"shoppingSelect\"  name=\"cartOption\">\r\n");
      out.write("							<option value=\"0\"> ---------------- 옵션 ---------------- &nbsp; </option>\r\n");
      out.write("							<!--  <option><span id=\"productOptionSpan2\"></span></option>\r\n");
      out.write("							<option><span id=\"productOptionSpan2\"></span></option> -->\r\n");
      out.write("						</select>\r\n");
      out.write("						\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>구매수량</td>\r\n");
      out.write("					<td>\r\n");
      out.write("						<div class=\"length\">\r\n");
      out.write("							<input type=\"text\" name=\"cartQty\" value=\"1\" readonly>  \r\n");
      out.write("							<a href=\"#a\" id=\"plus\">증가</a>\r\n");
      out.write("							<a href=\"#a\" id=\"minus\">감소</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</td>\r\n");
      out.write("					\r\n");
      out.write("				</tr>\r\n");
      out.write("				\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>배송비</td>\r\n");
      out.write("					<td>2500원  (50,000원 구매시 무료)</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>총가격</td>\r\n");
      out.write("					<td class=\"total\">\r\n");
      out.write("					<b></b>원\r\n");
      out.write("					<!-- <b><span id=\"productTotalSpan\"></span></b>원 -->\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"btnDiv items\">\r\n");
      out.write("			<input type=\"button\" id=\"wishListBtn\" value=\"찜하기\"> \r\n");
      out.write("			<input type=\"button\" id=\"cartBtn\" value=\"장바구니\"> \r\n");
      out.write("			<input type=\"button\" id=\"purchaseBtn\" value=\"구매하기\">\r\n");
      out.write("				<!-- <a href=\"#a\">장바구니</a>\r\n");
      out.write("				<a href=\"#a\">구매하기</a> -->\r\n");
      out.write("		</div>\r\n");
      out.write("			\r\n");
      out.write("	</div>\r\n");
      out.write("</form>		\r\n");
      out.write("	\r\n");
      out.write("	<div id=\"detailBottom\">\r\n");
      out.write("		<div id=\"detailInfoName\"><span>상품정보</span></div>\r\n");
      out.write("		<div id=\"detailReviewName\"><span>상품후기</span></div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div id=\"DetailInfoDiv\">\r\n");
      out.write("		<div id=\"productDetailInfoDiv\"></div>\r\n");
      out.write("	</div>	\r\n");
      out.write("	\r\n");
      out.write("	<div id=\"reviewDiv\">\r\n");
      out.write("		<form id=\"reviewForm\">\r\n");
      out.write("			<table id=\"reviewTable\" class=\"table\">\r\n");
      out.write("				<thead>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td colspan=\"4\">\r\n");
      out.write("							<div>\r\n");
      out.write("								<input type=\"radio\" class=\"reviewLike\" id=\"like1\" name=\"reviewLike\" value=\"1\">\r\n");
      out.write("								<label for=\"like1\">\r\n");
      out.write("									<img width=\"20px\" height=\"20px\" src=\"https://cdn-icons-png.flaticon.com/512/1163/1163655.png\">\r\n");
      out.write("								</label>\r\n");
      out.write("								<input type=\"radio\" class=\"reviewLike\" id=\"like2\" name=\"reviewLike\" value=\"2\">\r\n");
      out.write("								<label for=\"like2\">\r\n");
      out.write("									<img width=\"20px\" height=\"20px\" src=\"https://cdn-icons-png.flaticon.com/512/1163/1163655.png\">\r\n");
      out.write("									<img width=\"20px\" height=\"20px\" src=\"https://cdn-icons-png.flaticon.com/512/1163/1163655.png\">\r\n");
      out.write("								</label>\r\n");
      out.write("								<input type=\"radio\" class=\"reviewLike\" id=\"like3\" name=\"reviewLike\" value=\"3\">\r\n");
      out.write("								<label for=\"like3\">\r\n");
      out.write("									<img width=\"20px\" height=\"20px\" src=\"https://cdn-icons-png.flaticon.com/512/1163/1163655.png\">\r\n");
      out.write("									<img width=\"20px\" height=\"20px\" src=\"https://cdn-icons-png.flaticon.com/512/1163/1163655.png\">\r\n");
      out.write("									<img width=\"20px\" height=\"20px\" src=\"https://cdn-icons-png.flaticon.com/512/1163/1163655.png\">\r\n");
      out.write("								</label>\r\n");
      out.write("								<input type=\"radio\" class=\"reviewLike\" id=\"like4\" name=\"reviewLike\" value=\"4\">\r\n");
      out.write("								<label for=\"like4\">\r\n");
      out.write("									<img width=\"20px\" height=\"20px\" src=\"https://cdn-icons-png.flaticon.com/512/1163/1163655.png\">\r\n");
      out.write("									<img width=\"20px\" height=\"20px\" src=\"https://cdn-icons-png.flaticon.com/512/1163/1163655.png\">\r\n");
      out.write("									<img width=\"20px\" height=\"20px\" src=\"https://cdn-icons-png.flaticon.com/512/1163/1163655.png\">\r\n");
      out.write("									<img width=\"20px\" height=\"20px\" src=\"https://cdn-icons-png.flaticon.com/512/1163/1163655.png\">\r\n");
      out.write("								</label>\r\n");
      out.write("								<input type=\"radio\" class=\"reviewLike\" id=\"like5\" name=\"reviewLike\" value=\"5\">\r\n");
      out.write("								<label for=\"like5\">\r\n");
      out.write("									<img width=\"20px\" height=\"20px\" src=\"https://cdn-icons-png.flaticon.com/512/1163/1163655.png\">\r\n");
      out.write("									<img width=\"20px\" height=\"20px\" src=\"https://cdn-icons-png.flaticon.com/512/1163/1163655.png\">\r\n");
      out.write("									<img width=\"20px\" height=\"20px\" src=\"https://cdn-icons-png.flaticon.com/512/1163/1163655.png\">\r\n");
      out.write("									<img width=\"20px\" height=\"20px\" src=\"https://cdn-icons-png.flaticon.com/512/1163/1163655.png\">\r\n");
      out.write("									<img width=\"20px\" height=\"20px\" src=\"https://cdn-icons-png.flaticon.com/512/1163/1163655.png\">\r\n");
      out.write("								</label><br>\r\n");
      out.write("							</div>\r\n");
      out.write("							<input type=\"hidden\" name=\"productCode\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productCode }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("							");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("							");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</thead>\r\n");
      out.write("				<tbody></tbody>\r\n");
      out.write("			</table>\r\n");
      out.write("		</form>\r\n");
      out.write("		<div id=\"boardPaging\"></div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\"> //온로드할때 바로 이 부분이 실행되어야 해서 디테일jsp로 옮겨줌\r\n");
      out.write("$(function(){\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url: '/milkyWayForest/shopping/getShoppingDetail',  \r\n");
      out.write("		type: 'post',\r\n");
      out.write("		data: 'productCode=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productCode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("', // 이걸 추가해주고 컨트롤러에 productCode를 리퀘스트파람으로 가져간다. \r\n");
      out.write("		dataType: 'json',  \r\n");
      out.write("		success : function(data) {\r\n");
      out.write("		\r\n");
      out.write("		// console.log(JSON.stringify(data));\r\n");
      out.write("				\r\n");
      out.write("		$.each(data, function(index,items) {		\r\n");
      out.write("			$('#korsubjectSpan').text(items.productName);\r\n");
      out.write("			$('#engsubjectSpan').text(items.productEngName);\r\n");
      out.write("			$('#productSmallinfoSpan').text(items.productSmallInfo);\r\n");
      out.write("			$('#productpriceSpan').text(items.productUnit.toLocaleString())+\" 원\";\r\n");
      out.write("			/* $('#productOptionSpan2').text(items.productOption);\r\n");
      out.write("			$('#productOptionSpan2').text(items.productOption); */\r\n");
      out.write("			/* $('#productTotalSpan').text((items.productUnit)*parseInt($('.length input').val())); */\r\n");
      out.write("			$('#productDetailInfoDiv').text(items.productDetailInfo);	\r\n");
      out.write("			$('#categoryDiv').val(items.category);\r\n");
      out.write("			\r\n");
      out.write("			//사진 나타나게 하기(인덱스별로 조정)\r\n");
      out.write("			if(index==0) {  // 여기 인덱스는 위에 each 문의 인덱스. 우리가 데이터를 가져올때 이미지는 여러개(프로덕트코드만 같고 이미지명은 뒤에 _1 이런식으로 다른 이미지들)가져오니깐 그 이미지네임에 조건을 붙여서 써주기위해 인덱스라는 순번을 붙여준것\r\n");
      out.write("				$('#bigImg').attr('src', '/milkyWayForest/productImage/'+items.productImageName);\r\n");
      out.write("				$('#img1').attr('src', '/milkyWayForest/productImage/'+items.productImageName);\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			else if(index==1) {  // 사진이 여러장일때만 li태그가 붙는다. 여러장이 아닐때는 else if 부분을 주석해야만 개발자도구에서 li태그가 붙는걸 확인할수 있다.\r\n");
      out.write("				// 어펜드라는 속성은 항상 맨끝에 붙여주는 역할을 하기때문에 아래와 같이 ul태그 에 어펜드 li속성을 붙이면 \r\n");
      out.write("				//자동으로 우리가 폼태그 안에 첫번째 li태그 밑에 두번째 li 태그로 생성되게 된다.\r\n");
      out.write("				//어펜드로 하는 이유는 우리가 productImageName 이 올 때만 이미지를 붙여줄꺼라서(동적변환이 일어나게 하려고) 어펜드를 붙여준것.\r\n");
      out.write("				//상품사진이 만약 1개만 있다면 이부분에는 사진이 안 붙을것.\r\n");
      out.write("				\r\n");
      out.write("				$('.imgList').append($('<li>').append($('<img>', { \r\n");
      out.write("					src: '/milkyWayForest/productImage/'+items.productImageName,\r\n");
      out.write("					id: 'img2'\r\n");
      out.write("				})));\r\n");
      out.write("			\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			 else if(index==2) {\r\n");
      out.write("				$('.imgList').append($('<li>').append($('<img>' , { \r\n");
      out.write("					src: '/milkyWayForest/productImage/'+items.productImageName,\r\n");
      out.write("					id: 'img3'\r\n");
      out.write("				})));\r\n");
      out.write("				\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			 else if(index==3) {\r\n");
      out.write("				$('.imgList').append($('<li>').append($('<img>' , { \r\n");
      out.write("					src: '/milkyWayForest/productImage/'+items.productImageName,\r\n");
      out.write("					id: 'img4'\r\n");
      out.write("				})));\r\n");
      out.write("					\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			 else if(index==4) {\r\n");
      out.write("				$('.imgList').append($('<li>').append($('<img>' , { \r\n");
      out.write("					src: '/milkyWayForest/productImage/'+items.productImageName,\r\n");
      out.write("					id: 'img5'\r\n");
      out.write("				})));\r\n");
      out.write("					\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			 else if(index==5) {\r\n");
      out.write("				$('.imgList').append($('<li>').append($('<img>' , { \r\n");
      out.write("					src: '/milkyWayForest/productImage/'+items.productImageName,\r\n");
      out.write("					id: 'img6'\r\n");
      out.write("				})));\r\n");
      out.write("					\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			 else if(index==6) {\r\n");
      out.write("				$('.imgList').append($('<li>').append($('<img>' , { \r\n");
      out.write("					src: '/milkyWayForest/productImage/'+items.productImageName,\r\n");
      out.write("					id: 'img7'\r\n");
      out.write("				})));\r\n");
      out.write("					\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			//인덱스가 0번일때의 옵션과 총가격\r\n");
      out.write("			if(index==0) {\r\n");
      out.write("			$('.shoppingSelect').append($('<option>' ,{text: items.productOption, value:items.productOption })); //벨류가 실제로 넘겨주는값 텍스트는 눈에 보이는거\r\n");
      out.write("			$('.total b').append($('<span>', {\r\n");
      out.write("				id:'totalSpan',  \r\n");
      out.write("				text:((items.productUnit)*parseInt($('.length input').val())).toLocaleString()\r\n");
      out.write("			})); //이걸 안 넣으면 1개일때의 가격이 안나옴\r\n");
      out.write("		    	\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			//구매수량 늘어날때      수량 상품코드 장바구니 에 가져간다.(결제금액은 가져갈 필요 없다.) 장바구니 버튼을 눌렀을떄 에이작스를 실행해서 로케이션뒤에 장바구니코드를 붙여준다.\r\n");
      out.write("			$('#plus').click(function(){\r\n");
      out.write("				\r\n");
      out.write("				if(index==0){  // 인덱스가 0번일때만 아래 항목들이 수행되게 해라\r\n");
      out.write("					$('.length input').val(parseInt($('.length input').val())+1); // 이걸 인덱스 0번일때에 넣지 않고 바깥으로 빼면 사진의 갯수만큼 구매수량이 늘어나버림 \r\n");
      out.write("					$('.total b span').remove();  // 스팬태그를 지우고 다시 시작해줘라(클릭할때마다!)\r\n");
      out.write("					$('.total b').append($('<span>', {text:((items.productUnit)*parseInt($('.length input').val())).toLocaleString() //인덱스가 0번일때만 계산해줘라\r\n");
      out.write("					})); \r\n");
      out.write("				} \r\n");
      out.write("			});//#plus\r\n");
      out.write("			\r\n");
      out.write("			//구매수량 줄어들때\r\n");
      out.write("			$('#minus').click(function(){\r\n");
      out.write("				\r\n");
      out.write("				if(index==0) {\r\n");
      out.write("					$('.length input').val(parseInt($('.length input').val())-1);\r\n");
      out.write("						if($('.length input').val() < 1) {\r\n");
      out.write("							$('.length input').val(1);\r\n");
      out.write("						}\r\n");
      out.write("					$('.total b span').remove();\r\n");
      out.write("					$('.total b').append($('<span>', {text:((items.productUnit)*parseInt($('.length input').val())).toLocaleString()\r\n");
      out.write("					}));\r\n");
      out.write("					\r\n");
      out.write("				}		\r\n");
      out.write("			});//#minus\r\n");
      out.write("			\r\n");
      out.write("\r\n");
      out.write("		});//each\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		$('.shoppingDetailImg li:eq(0)').on(\"click\", $('.shoppingDetailImg li:eq(0)'), function(){\r\n");
      out.write("			//alert('0');\r\n");
      out.write("			$('#bigImg').prop(\"src\", $('.shoppingDetailImg li:eq(0) img').prop(\"src\"));\r\n");
      out.write("			$('.shoppingDetailImg li:not(0) img').css('border', '1px solid silver');\r\n");
      out.write("			$('.shoppingDetailImg li:eq(0) img').css('border', '1px solid  #154520');\r\n");
      out.write("		});\r\n");
      out.write("		$('.shoppingDetailImg li:eq(1)').on(\"click\", $('.shoppingDetailImg li:eq(1)'), function(){\r\n");
      out.write("			//alert('1');\r\n");
      out.write("			$('#bigImg').prop(\"src\", $('.shoppingDetailImg li:eq(1) img').prop(\"src\"));\r\n");
      out.write("			$('.shoppingDetailImg li:not(1) img').css('border', '1px solid silver');\r\n");
      out.write("			$('.shoppingDetailImg li:eq(1) img').css('border', '1px solid  #154520');\r\n");
      out.write("		});\r\n");
      out.write("		$('.shoppingDetailImg li:eq(2)').on(\"click\", $('.shoppingDetailImg li:eq(2)'), function(){\r\n");
      out.write("			//alert('2');\r\n");
      out.write("			$('#bigImg').prop(\"src\", $('.shoppingDetailImg li:eq(2) img').prop(\"src\"));\r\n");
      out.write("			$('.shoppingDetailImg li:not(2) img').css('border', '1px solid silver');\r\n");
      out.write("			$('.shoppingDetailImg li:eq(2) img').css('border', '1px solid  #154520');\r\n");
      out.write("		});\r\n");
      out.write("		$('.shoppingDetailImg li:eq(3)').on(\"click\", $('.shoppingDetailImg li:eq(3)'), function(){\r\n");
      out.write("			//alert('2');\r\n");
      out.write("			$('#bigImg').prop(\"src\", $('.shoppingDetailImg li:eq(3) img').prop(\"src\"));\r\n");
      out.write("			$('.shoppingDetailImg li:not(3) img').css('border', '1px solid silver');\r\n");
      out.write("			$('.shoppingDetailImg li:eq(3) img').css('border', '1px solid  #154520');\r\n");
      out.write("		});\r\n");
      out.write("		$('.shoppingDetailImg li:eq(4)').on(\"click\", $('.shoppingDetailImg li:eq(4)'), function(){\r\n");
      out.write("			//alert('2');\r\n");
      out.write("			$('#bigImg').prop(\"src\", $('.shoppingDetailImg li:eq(4) img').prop(\"src\"));\r\n");
      out.write("			$('.shoppingDetailImg li:not(4) img').css('border', '1px solid silver');\r\n");
      out.write("			$('.shoppingDetailImg li:eq(4) img').css('border', '1px solid  #154520');\r\n");
      out.write("		});\r\n");
      out.write("		$('.shoppingDetailImg li:eq(5)').on(\"click\", $('.shoppingDetailImg li:eq(5)'), function(){\r\n");
      out.write("			//alert('2');\r\n");
      out.write("			$('#bigImg').prop(\"src\", $('.shoppingDetailImg li:eq(5) img').prop(\"src\"));\r\n");
      out.write("			$('.shoppingDetailImg li:not(5) img').css('border', '1px solid silver');\r\n");
      out.write("			$('.shoppingDetailImg li:eq(5) img').css('border', '1px solid  #154520');\r\n");
      out.write("\r\n");
      out.write("		}); //li:eq(5)\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		if($('#categoryDiv').val() == '원두') {\r\n");
      out.write("			$('#shoppingDetailCategory').append($('<a>', {\r\n");
      out.write("				text: '원두 / 차',\r\n");
      out.write("				href: '/milkyWayForest/shopping/beanNTea'\r\n");
      out.write("			})).append(' > ').append($('<a>', {\r\n");
      out.write("				text: '원두',\r\n");
      out.write("				href: '/milkyWayForest/shopping/beanList'\r\n");
      out.write("			}));\r\n");
      out.write("		} else if($('#categoryDiv').val() == '티') {\r\n");
      out.write("			$('#shoppingDetailCategory').append($('<a>', {\r\n");
      out.write("				text: '원두 / 차',\r\n");
      out.write("				href: '/milkyWayForest/shopping/beanNTea'\r\n");
      out.write("			})).append(' > ').append($('<a>', {\r\n");
      out.write("				text: '차',\r\n");
      out.write("				href: '/milkyWayForest/shopping/teaList'\r\n");
      out.write("			}));\r\n");
      out.write("		} else if($('#categoryDiv').val() == '머그') {\r\n");
      out.write("			$('#shoppingDetailCategory').append($('<a>', {\r\n");
      out.write("				text: '상품',\r\n");
      out.write("				href: '/milkyWayForest/shopping/product'\r\n");
      out.write("			})).append(' > ').append($('<a>', {\r\n");
      out.write("				text: '머그',\r\n");
      out.write("				href: '/milkyWayForest/shopping/mugList'\r\n");
      out.write("			}));\r\n");
      out.write("		} else if($('#categoryDiv').val() == '글라스') {\r\n");
      out.write("			$('#shoppingDetailCategory').append($('<a>', {\r\n");
      out.write("				text: '상품',\r\n");
      out.write("				href: '/milkyWayForest/shopping/product'\r\n");
      out.write("			})).append(' > ').append($('<a>', {\r\n");
      out.write("				text: '글라스',\r\n");
      out.write("				href: '/milkyWayForest/shopping/glassList'\r\n");
      out.write("			}));\r\n");
      out.write("		} else if($('#categoryDiv').val() == '플라스틱 텀블러') {\r\n");
      out.write("			$('#shoppingDetailCategory').append($('<a>', {\r\n");
      out.write("				text: '상품',\r\n");
      out.write("				href: '/milkyWayForest/shopping/product'\r\n");
      out.write("			})).append(' > ').append($('<a>', {\r\n");
      out.write("				text: '플라스틱 텀블러',\r\n");
      out.write("				href: '/milkyWayForest/shopping/plasticTumblrList'\r\n");
      out.write("			}));\r\n");
      out.write("		} else if($('#categoryDiv').val() == '스테인리스 텀블러') {\r\n");
      out.write("			$('#shoppingDetailCategory').append($('<a>', {\r\n");
      out.write("				text: '상품',\r\n");
      out.write("				href: '/milkyWayForest/shopping/product'\r\n");
      out.write("			})).append(' > ').append($('<a>', {\r\n");
      out.write("				text: '스테인리스 텀블러',\r\n");
      out.write("				href: '/milkyWayForest/shopping/stainlessTumblrList'\r\n");
      out.write("			}));\r\n");
      out.write("		} else if($('#categoryDiv').val() == '보온병') {\r\n");
      out.write("			$('#shoppingDetailCategory').append($('<a>', {\r\n");
      out.write("				text: '상품',\r\n");
      out.write("				href: '/milkyWayForest/shopping/product'\r\n");
      out.write("			})).append(' > ').append($('<a>', {\r\n");
      out.write("				text: '보온병',\r\n");
      out.write("				href: '/milkyWayForest/shopping/thermosList'\r\n");
      out.write("			}));\r\n");
      out.write("		} else if($('#categoryDiv').val() == '커피용품') {\r\n");
      out.write("			$('#shoppingDetailCategory').append($('<a>', {\r\n");
      out.write("				text: '상품',\r\n");
      out.write("				href: '/milkyWayForest/shopping/product'\r\n");
      out.write("			})).append(' > ').append($('<a>', {\r\n");
      out.write("				text: '커피용품',\r\n");
      out.write("				href: '/milkyWayForest/shopping/coffeeEtcList'\r\n");
      out.write("			}));\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		}, //getShoppingDetail success\r\n");
      out.write("\r\n");
      out.write("		error: function(err) {\r\n");
      out.write("			console.log(err);\r\n");
      out.write("		}\r\n");
      out.write("	});	//getShoppingDetail 에이작스\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	//장바구니 버튼 클릭시\r\n");
      out.write("	$('#cartBtn').click(function(){\r\n");
      out.write("		if($('.shoppingSelect').val()=='0') {\r\n");
      out.write("			alert('상품 옵션을 선택해주세요.');\r\n");
      out.write("		} else if(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memId==null}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(") {\r\n");
      out.write("			alert('로그인 해주세요');\r\n");
      out.write("			location.href=\"/milkyWayForest/login/loginForm\";\r\n");
      out.write("		\r\n");
      out.write("		}else{\r\n");
      out.write("		\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url: '/milkyWayForest/shopping/productSelect',  \r\n");
      out.write("				type: 'post',\r\n");
      out.write("				data: 'productCode=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productCode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("', //'id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("',  \r\n");
      out.write("				 \r\n");
      out.write("				success : function(data) {  //알아서 자료형을 맞춰줌\r\n");
      out.write("					console.log(JSON.stringify(data));\r\n");
      out.write("					\r\n");
      out.write("						\r\n");
      out.write("					if(data !=0) {\r\n");
      out.write("						if(confirm(\"이미 장바구니에 있는 상품입니다. 장바구니로 이동하시겠습니까?\")){\r\n");
      out.write("							location.href= \"/milkyWayForest/cart\";\r\n");
      out.write("						}\r\n");
      out.write("					}\r\n");
      out.write("					else { \r\n");
      out.write("					\r\n");
      out.write("						$.ajax({\r\n");
      out.write("						url: '/milkyWayForest/cart/cartInsert',\r\n");
      out.write("						type: 'post',\r\n");
      out.write("						data: $('#shoppingDetailForm').serialize(),\r\n");
      out.write("						\r\n");
      out.write("						success : function() {  //에이작스는 성공만하면 success 를 수행할수 있음 따라서 받아오는 데이터 타입이 없어도 됨. 바로 카트.jsp 로 넘겨준다.  \r\n");
      out.write("							if(confirm(\"장바구니로 이동하시겠습니까?\")){\r\n");
      out.write("								location.href= \"/milkyWayForest/cart\";\r\n");
      out.write("							}\r\n");
      out.write("						},\r\n");
      out.write("	\r\n");
      out.write("						error: function(err) {\r\n");
      out.write("							console.log(err);\r\n");
      out.write("						\r\n");
      out.write("						} \r\n");
      out.write("						}); //productSelect 에이작스\r\n");
      out.write("			\r\n");
      out.write("					} //cartBtn else 끝\r\n");
      out.write("			\r\n");
      out.write("				},	//success (cart/cartInsert)\r\n");
      out.write("			\r\n");
      out.write("			});	//shopping/productSelect 에이작스	\r\n");
      out.write("	\r\n");
      out.write("		}// option:eq(0) else			\r\n");
      out.write("	\r\n");
      out.write("	}); //cartBtn click 펑션\r\n");
      out.write("	\r\n");
      out.write("	// 구매하기 버튼 눌렀을 때\r\n");
      out.write("	$('#shoppingDetailForm #purchaseBtn').click(function(){\r\n");
      out.write("		if($('.shoppingSelect').val()=='0') {\r\n");
      out.write("			alert('상품 옵션을 선택해주세요.');\r\n");
      out.write("		} else if(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memId == null}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(") {\r\n");
      out.write("			alert('로그인 해주세요');\r\n");
      out.write("			location.href='/milkyWayForest/login/loginForm';\r\n");
      out.write("		} else {\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url: '/milkyWayForest/shopping/productSelect',  \r\n");
      out.write("				type: 'post',\r\n");
      out.write("				data: 'productCode=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productCode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("', //'id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("',  \r\n");
      out.write("				 \r\n");
      out.write("				success : function(data) {  //알아서 자료형을 맞춰줌\r\n");
      out.write("\r\n");
      out.write("					if(data !=0) {\r\n");
      out.write("						if(confirm(\"이미 장바구니에 있는 상품입니다. 장바구니로 이동하시겠습니까?\")) {\r\n");
      out.write("							location.href=\"/milkyWayForest/cart\";\r\n");
      out.write("						}			\r\n");
      out.write("					}\r\n");
      out.write("					else { \r\n");
      out.write("						$.ajax({\r\n");
      out.write("							url: '/milkyWayForest/payment/cartInsert',\r\n");
      out.write("							type: 'post',\r\n");
      out.write("							data: $('#shoppingDetailForm').serialize(),\r\n");
      out.write("							success: function(data) {\r\n");
      out.write("								// alert(data);\r\n");
      out.write("								location.href='/milkyWayForest/payment?cartCode='+data;\r\n");
      out.write("							},\r\n");
      out.write("							error: function(err) {\r\n");
      out.write("								console.log(err);\r\n");
      out.write("							}\r\n");
      out.write("						}); // /payment/cartInsert 에이작스\r\n");
      out.write("						\r\n");
      out.write("					} // data !=0 else\r\n");
      out.write("				},\r\n");
      out.write("				error: function(err) {\r\n");
      out.write("					console.log(err);\r\n");
      out.write("				}\r\n");
      out.write("			}); // /shopping/productSelect 에이작스\r\n");
      out.write("		}\r\n");
      out.write("	}); // purchaseBtn 클릭시\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url: '/milkyWayForest/shopping/getReview?pg=1',\r\n");
      out.write("		type: 'post',\r\n");
      out.write("		data: 'productCode=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productCode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("',\r\n");
      out.write("		success: function(data) {\r\n");
      out.write("			// alert(JSON.stringify(data));\r\n");
      out.write("			\r\n");
      out.write("			$.each(data.list, function(index, items){\r\n");
      out.write("				$('<tr>').append($('<td>',{\r\n");
      out.write("					id: 'reviewLike'+index\r\n");
      out.write("				})).append($('<td>',{\r\n");
      out.write("					text: items.reviewContent\r\n");
      out.write("				})).append($('<td>',{\r\n");
      out.write("					text: items.id\r\n");
      out.write("				})).append($('<td>',{\r\n");
      out.write("					text: items.reviewDate,\r\n");
      out.write("					style: 'font-size: 12px; color: #999;'\r\n");
      out.write("				})).appendTo($('#reviewTable tbody'));\r\n");
      out.write("				\r\n");
      out.write("				var reviewStar = '';\r\n");
      out.write("				\r\n");
      out.write("				for(var i=0; i< items.reviewLike; i++) {\r\n");
      out.write("					reviewStar += '<img width=\"20px\" height=\"20px\" src=\"https://cdn-icons-png.flaticon.com/512/1163/1163655.png\">';\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("				$('#reviewLike'+index).html(reviewStar);\r\n");
      out.write("				\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			$('#boardPaging').html(data.boardPaging);\r\n");
      out.write("			\r\n");
      out.write("		},\r\n");
      out.write("		error: function(err) {\r\n");
      out.write("			console.log(err);\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	$('#detailInfoName').click(function(){\r\n");
      out.write("		$('#DetailInfoDiv').css('display','block');\r\n");
      out.write("		$('#detailInfoName').css('border','1px solid #555');\r\n");
      out.write("		$('#detailInfoName').css('border-bottom','0');\r\n");
      out.write("		$('#reviewDiv').css('display','none');\r\n");
      out.write("		$('#detailReviewName').css('border','0');\r\n");
      out.write("		$('#detailReviewName').css('border-bottom','1px solid #555');\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	$('#detailReviewName').click(function(){\r\n");
      out.write("		$('#DetailInfoDiv').css('display', 'none');\r\n");
      out.write("		$('#detailInfoName').css('border','0');\r\n");
      out.write("		$('#detailInfoName').css('border-bottom','1px solid #555');\r\n");
      out.write("		$('#reviewDiv').css('display', 'block');\r\n");
      out.write("		$('#detailReviewName').css('border','1px solid #555');\r\n");
      out.write("		$('#detailReviewName').css('border-bottom','0');\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	$('#reivewInsertBtn').click(function(){\r\n");
      out.write("		if($('#reviewContent').val() == ''){\r\n");
      out.write("			alert('상품후기를 입력하세요.');\r\n");
      out.write("		} else {\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url: '/milkyWayForest/shopping/reviewInsert',\r\n");
      out.write("				type: 'post',\r\n");
      out.write("				data: $('#reviewForm').serialize(),\r\n");
      out.write("				success: function(data) {\r\n");
      out.write("					$('#reviewTable tbody tr:eq(4)').remove();\r\n");
      out.write("					$('<tr>').append($('<td>',{\r\n");
      out.write("						html: $('label[for='+$('input[name=reviewLike]:checked').attr('id')+']').html()\r\n");
      out.write("					})).append($('<td>',{\r\n");
      out.write("						text: $('#reviewContent').val()\r\n");
      out.write("					})).append($('<td>',{\r\n");
      out.write("						text: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\r\n");
      out.write("					})).append($('<td>',{\r\n");
      out.write("						text: dateFormat(new Date()),\r\n");
      out.write("						style: 'font-size: 12px; color: #999;'\r\n");
      out.write("					})).prependTo($('#reviewTable tbody'));\r\n");
      out.write("					\r\n");
      out.write("					$('#reviewContent').val('');\r\n");
      out.write("					$('.reviewLike').prop('checked', 'false');\r\n");
      out.write("				},\r\n");
      out.write("				error: function(err) {\r\n");
      out.write("					console.log(err);\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		}\r\n");
      out.write("	})\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	$('#wishListBtn').click(function(){\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url: '/milkyWayForest/shopping/getWishProduct',\r\n");
      out.write("			type: 'post',\r\n");
      out.write("			data: 'productCode=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productCode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("',\r\n");
      out.write("			success: function(data) {\r\n");
      out.write("				//alert(data);\r\n");
      out.write("				if('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productCode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' == data) {\r\n");
      out.write("					if(confirm(\"이미 찜하기 목록에 있습니다. 찜하기 목록으로 이동하시겠습니까?\")) {\r\n");
      out.write("						location.href=\"/milkyWayForest/mypage/wishList?pg=1\";\r\n");
      out.write("					} \r\n");
      out.write("				} else {	\r\n");
      out.write("\r\n");
      out.write("					$.ajax({\r\n");
      out.write("						url: '/milkyWayForest/shopping/insertWishList',\r\n");
      out.write("						type: 'post',\r\n");
      out.write("						data: 'productCode=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productCode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("',\r\n");
      out.write("						success: function(data) {\r\n");
      out.write("							if(confirm(\"찜하기되었습니다. 찜하기 목록으로 이동하시겠습니까?\")) {\r\n");
      out.write("								location.href=\"/milkyWayForest/mypage/wishList?pg=1\";\r\n");
      out.write("							}\r\n");
      out.write("						},\r\n");
      out.write("						error: function(err) {\r\n");
      out.write("							console.log(err);\r\n");
      out.write("						}\r\n");
      out.write("					});\r\n");
      out.write("				}\r\n");
      out.write("			},\r\n");
      out.write("			error: function(err) {\r\n");
      out.write("				console.log(err);\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("}); //큰 function\r\n");
      out.write("\r\n");
      out.write("function boardPaging(page){\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url: \"/milkyWayForest/shopping/getReview?pg=\"+page,\r\n");
      out.write("		type: 'post',\r\n");
      out.write("		data: 'productCode=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productCode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("',\r\n");
      out.write("		success: function(data) {\r\n");
      out.write("			$('#reviewTable tbody').empty();\r\n");
      out.write("			$.each(data.list, function(index, items){\r\n");
      out.write("				$('<tr>').append($('<td>',{\r\n");
      out.write("					id: 'reviewLike'+index,\r\n");
      out.write("					style: 'font-weight: bold; color: red;'\r\n");
      out.write("				})).append($('<td>',{\r\n");
      out.write("					text: items.reviewContent\r\n");
      out.write("				})).append($('<td>',{\r\n");
      out.write("					text: items.id\r\n");
      out.write("				})).append($('<td>',{\r\n");
      out.write("					text: items.reviewDate,\r\n");
      out.write("					style: 'font-size: 12px; color: #999;'\r\n");
      out.write("				})).appendTo($('#reviewTable tbody'));\r\n");
      out.write("				\r\n");
      out.write("				var reviewStar = '';\r\n");
      out.write("				\r\n");
      out.write("				for(var i=0; i< items.reviewLike; i++) {\r\n");
      out.write("					reviewStar += '<img width=\"20px\" height=\"20px\" src=\"https://cdn-icons-png.flaticon.com/512/1163/1163655.png\">';\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("				$('#reviewLike'+index).html(reviewStar);\r\n");
      out.write("				\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			$('#boardPaging').html(data.boardPaging);\r\n");
      out.write("			\r\n");
      out.write("		},\r\n");
      out.write("		error: function(err) {\r\n");
      out.write("			console.log(err);\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function dateFormat(date) {\r\n");
      out.write("    let month = date.getMonth() + 1;\r\n");
      out.write("    let day = date.getDate();\r\n");
      out.write("    let hour = date.getHours();\r\n");
      out.write("    let minute = date.getMinutes();\r\n");
      out.write("    let second = date.getSeconds();\r\n");
      out.write("\r\n");
      out.write("    month = month >= 10 ? month : '0' + month;\r\n");
      out.write("    day = day >= 10 ? day : '0' + day;\r\n");
      out.write("    hour = hour >= 10 ? hour : '0' + hour;\r\n");
      out.write("    minute = minute >= 10 ? minute : '0' + minute;\r\n");
      out.write("    second = second >= 10 ? second : '0' + second;\r\n");
      out.write("\r\n");
      out.write("    return date.getFullYear() + '-' + month + '-' + day + ' ' + hour + ':' + minute + ':' + second;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /shopping/shoppingDetail.jsp(167,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memId == null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("								<textarea id=\"reviewContent\" name=\"reviewContent\" placeholder=\"로그인 후 후기를 작성할 수 있습니다.\" disabled></textarea>\r\n");
          out.write("								<input type=\"button\" id=\"reivewInsertBtn\" class=\"btn\" value=\"리뷰 등록\" disabled>\r\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /shopping/shoppingDetail.jsp(171,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memId != null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("								<textarea id=\"reviewContent\" name=\"reviewContent\"></textarea>\r\n");
          out.write("								<input type=\"button\" id=\"reivewInsertBtn\" class=\"btn\" value=\"리뷰 등록\">\r\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
