/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-12-07 06:38:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class loginOk_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("img {\r\n");
      out.write("	width: 70px;\r\n");
      out.write("	height: 70px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.memName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("님 로그인\r\n");
      out.write("<br><br>\r\n");
      out.write("\r\n");
      out.write("<input type=\"button\" value=\"로그아웃\" id=\"logoutBtn\">\r\n");
      out.write("<input type=\"button\" value=\"회원정보수정\" onclick=\"location.href='/MQBProject/member/modifyForm.do'\">\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$('#logoutBtn').click(function(){\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url: '/MQBProject/member/logout.do',\r\n");
      out.write("		type: 'post',\r\n");
      out.write("		success: function(){\r\n");
      out.write("			alert('로그아웃');\r\n");
      out.write("			location.href=\"/MQBProject/index.jsp\";\r\n");
      out.write("		},\r\n");
      out.write("		error: function(err){\r\n");
      out.write("			console.log(err);	\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//회원가입 유효성 검사\r\n");
      out.write("$('#memberWriteForm #memberWriteBtn').click(function(){\r\n");
      out.write("	\r\n");
      out.write("//	$('#idDiv').empty();\r\n");
      out.write("//	$('#pwdDiv').empty();\r\n");
      out.write("//	$('#pwdReDiv').empty();\r\n");
      out.write("//	$('#nameDiv').empty();\r\n");
      out.write("//	$('#nickNameDiv').empty();\r\n");
      out.write("	$('#emailDiv').empty();\r\n");
      out.write("//	$('#athDiv').empty();\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	var nameForm = /^[가-힣]{2,4}$/;\r\n");
      out.write("	var nicknameForm = /^[\\w\\Wㄱ-ㅎㅏ-ㅣ가-힣]{2,20}$/;\r\n");
      out.write("	var telForm = /^01([0|1|6|7|8|9])-?([0-9]{3,4})-?([0-9]{4})$/;\r\n");
      out.write("	var pwdForm = /^(?=.*[a-zA-Z])(?=.*[!@#$%^*+=-])(?=.*[0-9]).{8,16}$/; //정규표현식\r\n");
      out.write("	\r\n");
      out.write("		\r\n");
      out.write("	var name = $('#memberWriteForm #memberWriteName').val();	\r\n");
      out.write("	var nickname = $('#memberWriteForm #memberWriteNick').val();\r\n");
      out.write("	var tel1 = $('#memberWriteForm #writeTel1').val();\r\n");
      out.write("	var tel2 = $('#memberWriteForm #writeTel2').val();\r\n");
      out.write("	var tel3 = $('#memberWriteForm #writeTel3').val();\r\n");
      out.write("	var tel = tel1 + \"-\" +  tel2 + \"-\" + tel3;\r\n");
      out.write("	var pwd = $('#memberWriteForm #memberWritePwd').val();\r\n");
      out.write("	\r\n");
      out.write("	if($('#memberWriteForm #memberWriteId').val() == ''){\r\n");
      out.write("		$('#memberWriteForm #emailDiv').html('아이디 입력');\r\n");
      out.write("		$('#memberWriteForm #emailDiv').css('color','red');\r\n");
      out.write("		$('#memberWriteId').focus();\r\n");
      out.write("	}else if($('#memberWriteForm #memberWritePwd').val() == ''){\r\n");
      out.write("		$('#memberWriteForm #emailDiv').html('비밀번호 입력');\r\n");
      out.write("		$('#memberWriteForm #emailDiv').css('color','red');\r\n");
      out.write("		$('#memberWritePwd').focus();\r\n");
      out.write("	}else if(!pwdForm.test(pwd)){\r\n");
      out.write("		$('#memberWriteForm #emailDiv').html('잘못된 비밀번호 형식입니다.');\r\n");
      out.write("		$('#memberWriteForm #emailDiv').css('color','red');\r\n");
      out.write("		$('#memberWritePwd').focus();\r\n");
      out.write("	}else if($('#memberWriteForm #memberWritePwd').val() != $('#memberWriteRePwd').val()){\r\n");
      out.write("		$('#memberWriteForm #emailDiv').html('비밀번호 틀림');\r\n");
      out.write("		$('#memberWriteForm #emailDiv').css('color','red');\r\n");
      out.write("		$('#memberWritePwd').focus();\r\n");
      out.write("	}else if($('#memberWriteForm #memberWriteName').val() == ''){\r\n");
      out.write("		$('#memberWriteForm #emailDiv').html('이름 입력');\r\n");
      out.write("		$('#memberWriteForm #emailDiv').css('color','red');\r\n");
      out.write("		$('#memberWriteName').focus();\r\n");
      out.write("	}else if(!nameForm.test(name)){\r\n");
      out.write("		$('#memberWriteForm #emailDiv').html('잘못된 이름 형식입니다.');\r\n");
      out.write("		$('#memberWriteForm #emailDiv').css('color','red');\r\n");
      out.write("		$('#memberWriteName').focus();\r\n");
      out.write("	}else if($('#memberWriteForm #memberWriteNick').val() == ''){\r\n");
      out.write("		$('#memberWriteForm #emailDiv').html('닉네임 입력');\r\n");
      out.write("		$('#memberWriteForm #emailDiv').css('color','red');\r\n");
      out.write("		$('#memberWriteNick').focus();\r\n");
      out.write("	}else if(!nicknameForm.test(nickname)){\r\n");
      out.write("		$('#memberWriteForm #emailDiv').html('잘못된 닉네임 형식입니다.');\r\n");
      out.write("		$('#memberWriteForm #emailDiv').css('color','red');\r\n");
      out.write("		$('#memberWriteNick').focus();\r\n");
      out.write("	}else if(!telForm.test(tel)){\r\n");
      out.write("		$('#memberWriteForm #emailDiv').html('잘못된 번호 형식입니다.');\r\n");
      out.write("		$('#memberWriteForm #emailDiv').css('color','red');\r\n");
      out.write("	}else if($(\"#memberWriteForm #writeQuestion option\").index( $(\"#memberWriteForm #writeQuestion option:selected\") >= 1)){\r\n");
      out.write("		$('#writeAnwer').removeAttr('disabled');\r\n");
      out.write("		\r\n");
      out.write("	\r\n");
      out.write("	}else if($('#memberWriteForm #memberWriteEmail').val() == ''){\r\n");
      out.write("		$('#memberWriteForm #emailDiv').html('이메일을 입력해주세요');\r\n");
      out.write("		$('#memberWriteForm #emailDiv').css('color','red');\r\n");
      out.write("	}else if($('#memberWriteForm .gender').val() == ''){\r\n");
      out.write("		$('memberWriteForm #emailDiv').html('성별을 체크해주세요');\r\n");
      out.write("	\r\n");
      out.write("	}else if($('#memberWriteForm #memberWriteEmail1').val() == ''){\r\n");
      out.write("		$('#memberWriteForm #emailDiv').html('이메일을 입력해주세요');\r\n");
      out.write("		$('#memberWriteForm #emailDiv').css('color','red');\r\n");
      out.write("	}else if($('#memberWriteForm #athntNmbr').val() == ''){\r\n");
      out.write("		$('#memberWriteForm #emailDiv').html('이메일 인증 해주세요');\r\n");
      out.write("		$('#memberWriteForm #emailDiv').css('color','red');\r\n");
      out.write("	}else{\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("//		if($('#memberWriteForm #writeAnwer').val() == ''){\r\n");
      out.write("//		\r\n");
      out.write("//			$('#memberWriteForm #writeAnwer').val('false');\r\n");
      out.write("//			$('#memberWriteForm #writeQuestion').val('false').prop('selected',true);\r\n");
      out.write("//		}\r\n");
      out.write("//		 if($('#memberWriteForm #joinPath').val() == ''){\r\n");
      out.write("//			$('#memberWriteForm #joinPath').val('false');\r\n");
      out.write("/*		$.ajax({\r\n");
      out.write("			url: '/milkyWayForest/write/write',                url의 주소로 \r\n");
      out.write("			type:'post',\r\n");
      out.write("			data: $('#memberWriteForm').serialize(),\r\n");
      out.write("			success: function(){\r\n");
      out.write("				alert('회원 가입 등록');\r\n");
      out.write("				$('#memberWriteForm').submit();\r\n");
      out.write("			},\r\n");
      out.write("			error:function(err){\r\n");
      out.write("				console.log(err);\r\n");
      out.write("			}\r\n");
      out.write("		}); */\r\n");
      out.write("		\r\n");
      out.write("		$('#memberWriteForm').submit();\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("});\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
