/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-12-15 03:32:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mypageTopNav_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/milkyWayForest/css/mypage.css\">\r\n");
      out.write("\r\n");
      out.write("<div id=\"topNav-wrapper\">\r\n");
      out.write("	<input type=\"hidden\" id=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("	<div id=\"myInfoBox-wrapper\" class=\"item card\">\r\n");
      out.write("		<div class=\"row no-gutters\">\r\n");
      out.write("			<div id=\"myInfoPhoto\" class=\"col-md-4\">\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div id=\"myInfoDescript\" class=\"col-md-8\">\r\n");
      out.write("				<div class=\"card-body\">\r\n");
      out.write("					<h5 class=\"card-title\">한눈에 내 정보 보기</h5>\r\n");
      out.write("					<p class=\"card-text\">안녕하세요. 저희 은하숲을 이용해주셔서 감사합니다.<br>\r\n");
      out.write("						<strong>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong>님은\r\n");
      out.write("						<a class=\"topnavATag\" href=\"/milkyWayForest/mypage/mypageRating\"><strong id=\"memberGrade\"></strong></a>등급입니다.\r\n");
      out.write("					</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div><!-- 내 정보 -->\r\n");
      out.write("\r\n");
      out.write("	<div id=\"myBenefit-wrapper\" class=\"item\">\r\n");
      out.write("		<ul class=\"list-group\">\r\n");
      out.write("			<li class=\"list-group-item list-group-item-action\">\r\n");
      out.write("				<span>사용가능한 쿠폰\r\n");
      out.write("					<a href=\"/milkyWayForest/mypage/mypageCoupon\" id=\"countCoupon\"></a>장\r\n");
      out.write("				</span>\r\n");
      out.write("			</li>\r\n");
      out.write("			<li class=\"list-group-item list-group-item-action\">\r\n");
      out.write("				<span>사용가능한 적립금\r\n");
      out.write("					<a href=\"/milkyWayForest/mypage/mypageCpnPnts?pg=1\" id=\"savedMoney\"></a>원\r\n");
      out.write("				</span>\r\n");
      out.write("			</li>\r\n");
      out.write("			<li class=\"list-group-item list-group-item-action\">\r\n");
      out.write("				<span>총 주문 횟수\r\n");
      out.write("					<a href=\"/milkyWayForest/mypage/mypageOrderList?pg=1\" id=\"countPayment\"></a>회\r\n");
      out.write("				</span>\r\n");
      out.write("			</li>\r\n");
      out.write("			<li class=\"list-group-item list-group-item-action\">\r\n");
      out.write("				<span>총 주문 금액\r\n");
      out.write("					<a href=\"/milkyWayForest/mypage/mypageOrderList?pg=1\" id=\"paidTotal\"></a>원\r\n");
      out.write("				</span>\r\n");
      out.write("			</li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("//회원정보 불러오기 \r\n");
      out.write("$(function(){\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url: '/milkyWayForest/mypage/getMypageMyInfo',\r\n");
      out.write("		type: 'post',\r\n");
      out.write("		data: {'id' : $('#id').val()},\r\n");
      out.write("		success: function(data){\r\n");
      out.write("			console.log(JSON.stringify(data));\r\n");
      out.write("			$('#memberGrade').html(data.memberGrade);	\r\n");
      out.write("			\r\n");
      out.write("			if(data.memberGrade == 'welcome'){\r\n");
      out.write("				$('#myInfoPhoto').append($('<img>',{\r\n");
      out.write("					alt: data.memberGrade,\r\n");
      out.write("					class: 'card-img rounded float-left',\r\n");
      out.write("					src: '/milkyWayForest/image/'+data.memberGrade+'.png'\r\n");
      out.write("				}));\r\n");
      out.write("				\r\n");
      out.write("			}else{\r\n");
      out.write("				$('#myInfoPhoto').append($('<img>',{\r\n");
      out.write("					alt: data.memberGrade,\r\n");
      out.write("					class: 'card-img rounded float-left',\r\n");
      out.write("					src: '/milkyWayForest/image/'+data.memberGrade+'.PNG'\r\n");
      out.write("				}));\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			var savedMoney = data.savedMoney.toLocaleString();\r\n");
      out.write("			$('#savedMoney').html(savedMoney);\r\n");
      out.write("		},\r\n");
      out.write("		error: function(err){\r\n");
      out.write("			console.log(err);\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url: '/milkyWayForest/mypage/getPaymentInfo',\r\n");
      out.write("		type: 'post',\r\n");
      out.write("		success: function(data){\r\n");
      out.write("			console.log(JSON.stringify(data));\r\n");
      out.write("			$('#countCoupon').html(data.countCoupon);\r\n");
      out.write("			$('#countPayment').html(data.countPayment);	\r\n");
      out.write("			\r\n");
      out.write("			var paidTotal=0;\r\n");
      out.write("			\r\n");
      out.write("			if(data.paymentList == ''){\r\n");
      out.write("				$('#paidTotal').html('0');\r\n");
      out.write("				\r\n");
      out.write("			}else{\r\n");
      out.write("				$.each(data.paymentList, function(index, items) {\r\n");
      out.write("					console.log(items.payPrice);\r\n");
      out.write("					var payQty = items.payQty*1;\r\n");
      out.write("					var payPrice = items.payPrice*1;\r\n");
      out.write("					var payRate = items.payRate*1;\r\n");
      out.write("					\r\n");
      out.write("					paidTotal += payQty*payPrice*(1-payRate/100);\r\n");
      out.write("				});\r\n");
      out.write("				\r\n");
      out.write("				paidTotal = paidTotal.toLocaleString();\r\n");
      out.write("				$('#paidTotal').html(paidTotal);\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			\r\n");
      out.write("		},\r\n");
      out.write("		error: function(err){\r\n");
      out.write("			console.log(err);\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
