/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-12-15 07:12:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mypageMyOrderView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/milkyWayForest/css/mypage.css\">\r\n");
      out.write("\r\n");
      out.write("<form id=\"myOrderView\">\r\n");
      out.write("<div id=\"h1Div\"><h1 style=\"font-size: 35px;\">마이페이지</h1></div>\r\n");
      out.write("<div id=\"main-wrapper\">\r\n");
      out.write("	<div id=\"main-sideNav\" class=\"item\">\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "mypageSideNav.jsp", out, false);
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div id=\"main-topNav\" class=\"item\">\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "mypageTopNav.jsp", out, false);
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("	<input type=\"hidden\" id=\"paymentCode\" name=\"paymentCode\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${paymentCode }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("	<input type=\"hidden\" id=\"pg\" name=\"pg\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pg }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("	<input type=\"hidden\" id=\"id\" name=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("	\r\n");
      out.write("	<div id=\"myOrderView-wrapper\" class=\"item\">\r\n");
      out.write("		<div id=\"myOrderView1\">\r\n");
      out.write("			<div id=\"buttonWrap\">\r\n");
      out.write("				<input type=\"button\" id=\"reorderBtn\" class=\"btn\" value=\"재주문\">\r\n");
      out.write("				<input type=\"button\" id=\"orderCancleBtn\" class=\"btn\" value=\"주문취소\">\r\n");
      out.write("				<input type=\"button\" id=\"orderExchangeBtn\" class=\"btn\" value=\"교환신청\">\r\n");
      out.write("				<input type=\"button\" id=\"orderReturnBtn\" class=\"btn\" value=\"반품신청\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"navbar navbar-light\">\r\n");
      out.write("				<span class=\"mb-0\">주문 상세정보</span>			\r\n");
      out.write("			</div>\r\n");
      out.write("			<div>\r\n");
      out.write("				<table class=\"table\">\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>주문일자</th>\r\n");
      out.write("						<td id=\"payDate\"></td>\r\n");
      out.write("						<th>주문번호</th>\r\n");
      out.write("						<td id=\"paymentCode\"></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</table>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div>\r\n");
      out.write("				<table class=\"table border-bottom\" id=\"productInfoTable\">\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th scope=\"col\">상품번호</th>\r\n");
      out.write("						<th scope=\"col\">상품사진</th>\r\n");
      out.write("						<th scope=\"col\" width=\"200px;\">상품이름</th>\r\n");
      out.write("						<th scope=\"col\">상품금액(수량)</th>\r\n");
      out.write("						<th scope=\"col\">배송비</th>\r\n");
      out.write("						<th scope=\"col\">진행상태</th>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</table>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div id=\"orderChangeDiv\">\r\n");
      out.write("				<div class=\"navbar navbar-light\">\r\n");
      out.write("					<span id=\"orderChangeTitle\" class=\"mb-0\"></span>			\r\n");
      out.write("				</div>\r\n");
      out.write("				<table class=\"table border-bottom\">\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th id=\"orderChangeReason\" width=\"200px;\"></th>\r\n");
      out.write("						<td id=\"reason\"></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>상세사유</th>\r\n");
      out.write("						<td id=\"detailReason\"></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</table>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div id=\"myOrderView2\">\r\n");
      out.write("			<div class=\"navbar navbar-light\">\r\n");
      out.write("				<span class=\"mb-0\">주문/결제 금액 정보</span>			\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div id=\"paymentTotal\">\r\n");
      out.write("				<table class=\"table border-bottom\">\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th width=\"200px;\">총 상품금액</th>\r\n");
      out.write("						<td id=\"totalProductPrice\"></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>총 할인금액</th>\r\n");
      out.write("						<td id=\"totalSalePrice\"></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>배송비</th>\r\n");
      out.write("						<td id=\"shipPay\"></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>총 결제금액</th>\r\n");
      out.write("						<td id=\"totalPayPrice\"></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>적립금</th>\r\n");
      out.write("						<td id=\"savedMoney\"></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</table>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div id=\"myOrderView3\">\r\n");
      out.write("			<div class=\"navbar navbar-light\">\r\n");
      out.write("				<span class=\"mb-0\">배송지 정보</span>			\r\n");
      out.write("			</div>\r\n");
      out.write("			<div>\r\n");
      out.write("				<table class=\"table border-bottom\">\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th width=\"200px;\">수령인</th>\r\n");
      out.write("						<td id=\"payShipReceiver\"></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>연락처</th>\r\n");
      out.write("						<td id=\"payShipTel\"></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>배송지</th>\r\n");
      out.write("						<td>\r\n");
      out.write("							우편번호<span id=\"payShipZipcode\"></span><br>\r\n");
      out.write("							주소<span id=\"payShipAddr\"></span>\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>배송메모</th>\r\n");
      out.write("						<td id=\"shipMemo\"></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</table>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"myOrderView4\"></div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("</div><!-- main-wrapper -->\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<form id=\"cartInsertList\">\r\n");
      out.write("	<table id=\"cartInsertListTable\" >\r\n");
      out.write("	</table>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("	//배송상품 주문정보\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url: '/milkyWayForest/mypage/getMyOrderInfo',\r\n");
      out.write("		type: 'post',\r\n");
      out.write("		data: 'paymentCode='+$('#paymentCode').val(),\r\n");
      out.write("		success: function(data){\r\n");
      out.write("			//alert(JSON.stringify(data));\r\n");
      out.write("			//console.log(JSON.stringify(data));\r\n");
      out.write("			if(data.paymentList != ''){\r\n");
      out.write("				var payQty=0;\r\n");
      out.write("				var payPrice=0;\r\n");
      out.write("				var payRate=0;\r\n");
      out.write("				var shipPay=0;\r\n");
      out.write("				\r\n");
      out.write("				var totalProductPrice=0;\r\n");
      out.write("				var totalSalePrice=0;\r\n");
      out.write("				var totalPayPrice=0;\r\n");
      out.write("\r\n");
      out.write("				$.each(data.paymentList, function(index, items) {\r\n");
      out.write("					if(items.deliveryInfo=='입금대기중' || items.deliveryInfo=='결제완료' || items.deliveryInfo=='배송준비중' || items.deliveryInfo=='배송중'){\r\n");
      out.write("						$('#orderCancleBtn').show();\r\n");
      out.write("	\r\n");
      out.write("					}else if(items.deliveryInfo=='배송완료'){\r\n");
      out.write("						$('#orderExchangeBtn').show();\r\n");
      out.write("						$('#orderReturnBtn').show();\r\n");
      out.write("					}\r\n");
      out.write("					\r\n");
      out.write("					$('#myOrderView1 #payDate').html(items.payDate);\r\n");
      out.write("					$('#myOrderView1 #paymentCode').html(items.paymentCode);\r\n");
      out.write("					\r\n");
      out.write("					$('<tr>').append($('<td>',{\r\n");
      out.write("						text: items.productCode\r\n");
      out.write("					})).append($('<td>',{}).append($('<img>',{\r\n");
      out.write("						id: 'productImageName'+index,\r\n");
      out.write("						src: '/milkyWayForest/productImage/'+items.productImageName,\r\n");
      out.write("						width: '100px',\r\n");
      out.write("						heigiht: '100px'\r\n");
      out.write("					}))).append($('<td>',{\r\n");
      out.write("						text: items.productName\r\n");
      out.write("					})).append($('<td>',{\r\n");
      out.write("						text: items.payPrice+' ('+items.payQty+'개)'\r\n");
      out.write("					})).append($('<td>',{\r\n");
      out.write("						text: items.shipPay\r\n");
      out.write("					})).append($('<td>',{\r\n");
      out.write("						text: items.deliveryInfo\r\n");
      out.write("					})).appendTo($('#productInfoTable'));\r\n");
      out.write("					\r\n");
      out.write("					payQty = items.payQty*1;\r\n");
      out.write("					payPrice = items.payPrice*1;\r\n");
      out.write("					payRate = items.payRate*1;\r\n");
      out.write("					shipPay = items.shipPay*1;\r\n");
      out.write("					\r\n");
      out.write("					totalProductPrice += payQty*payPrice;\r\n");
      out.write("					totalSalePrice += payQty*payPrice*payRate/100;\r\n");
      out.write("					totalPayPrice += payQty*payPrice*(1-payRate/100);\r\n");
      out.write("					\r\n");
      out.write("					$('#myOrderView2 #totalProductPrice').html(totalProductPrice);\r\n");
      out.write("					$('#myOrderView2 #totalSalePrice').html(totalSalePrice);\r\n");
      out.write("					$('#myOrderView2 #shipPay').html(items.shipPay);\r\n");
      out.write("					$('#myOrderView2 #savedMoney').html(items.newSavedMoney);\r\n");
      out.write("\r\n");
      out.write("					var payShipTel = items.payShipTel1+\"-\"+items.payShipTel2+\"-\"+items.payShipTel3;\r\n");
      out.write("					var payShipAddr = items.payShipAddr1+\" \"+items.payShipAddr2\r\n");
      out.write("					\r\n");
      out.write("					$('#myOrderView3 #payShipReceiver').html(items.payShipReceiver);\r\n");
      out.write("					$('#myOrderView3 #payShipTel').html(payShipTel);\r\n");
      out.write("					$('#myOrderView3 #payShipZipcode').html(items.payShipReceiver);\r\n");
      out.write("					$('#myOrderView3 #payShipAddr').html(payShipAddr);\r\n");
      out.write("					$('#myOrderView3 #shipMemo').html(items.shipMemo);\r\n");
      out.write("				});\r\n");
      out.write("				\r\n");
      out.write("				totalPayPrice += shipPay;\r\n");
      out.write("				$('#myOrderView2 #totalPayPrice').html(totalPayPrice);\r\n");
      out.write("				\r\n");
      out.write("				$('#productInfoTable').rowspan(4);\r\n");
      out.write("				$('#productInfoTable').rowspan(5);\r\n");
      out.write("\r\n");
      out.write("				//재주문 정보 저장\r\n");
      out.write("				$.each(data.paymentList, function(index, items) {\r\n");
      out.write("					$('<tr>').append($('<td>').append($('<input>',{\r\n");
      out.write("						type: 'hidden',\r\n");
      out.write("						name: 'productCode',\r\n");
      out.write("						value: items.productCode\r\n");
      out.write("						\r\n");
      out.write("					})).append($('<input>',{\r\n");
      out.write("						type: 'hidden',\r\n");
      out.write("						name: 'cartOption',\r\n");
      out.write("						value: items.productOption\r\n");
      out.write("						\r\n");
      out.write("					})).append($('<input>',{\r\n");
      out.write("						type: 'hidden',\r\n");
      out.write("						name: 'cartQty',\r\n");
      out.write("						value: items.payQty\r\n");
      out.write("						\r\n");
      out.write("					}))).appendTo($('#cartInsertListTable'));\r\n");
      out.write("				});\r\n");
      out.write("\r\n");
      out.write("			}//if	\r\n");
      out.write("\r\n");
      out.write("		},\r\n");
      out.write("		error: function(err){\r\n");
      out.write("			console.log(err);\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("	//취소 교환 반품 사유\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url: '/milkyWayForest/mypage/getMyOrderCancelInfo',\r\n");
      out.write("		type: 'post',\r\n");
      out.write("		data: 'paymentCode='+$('#paymentCode').val(),\r\n");
      out.write("		success: function(data){\r\n");
      out.write("			//console.log(JSON.stringify(data));\r\n");
      out.write("			if(data.deliveryInfo != 'false'){\r\n");
      out.write("				if(data.deliveryInfo=='취소'){\r\n");
      out.write("					$('#orderChangeDiv').show();\r\n");
      out.write("					$('#orderChangeTitle').html('주문취소');\r\n");
      out.write("					$('#orderChangeReason').html('주문취소사유');\r\n");
      out.write("					$('#reason').html(data.reason);\r\n");
      out.write("					$('#detailReason').html(data.detailReason);\r\n");
      out.write("					\r\n");
      out.write("				}else if(data.deliveryInfo=='교환'){\r\n");
      out.write("					$('#orderChangeDiv').show();\r\n");
      out.write("					$('#orderChangeTitle').html('교환신청');\r\n");
      out.write("					$('#orderChangeReason').html('교환사유');\r\n");
      out.write("					$('#reason').html(data.reason);\r\n");
      out.write("					$('#detailReason').html(data.detailReason);\r\n");
      out.write("					\r\n");
      out.write("				}else if(data.deliveryInfo=='반품'){\r\n");
      out.write("					$('#orderChangeDiv').show();\r\n");
      out.write("					$('#orderChangeTitle').html('반품신청');\r\n");
      out.write("					$('#orderChangeReason').html('반품사유');\r\n");
      out.write("					$('#reason').html(data.reason);\r\n");
      out.write("					$('#detailReason').html(data.detailReason);\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("		},\r\n");
      out.write("		error: function(err){\r\n");
      out.write("			console.log(err);\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$('#myOrderView1').on('click','#reorderBtn',function(){\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url: '/milkyWayForest/cart/cartInsertList',\r\n");
      out.write("		type: 'post',\r\n");
      out.write("		data: $('#cartInsertList').serialize(),\r\n");
      out.write("		\r\n");
      out.write("		success : function() {\r\n");
      out.write("			if(confirm(\"장바구니로 이동하시겠습니까?\")){\r\n");
      out.write("				location.href= \"/milkyWayForest/cart\";\r\n");
      out.write("			}\r\n");
      out.write("		},\r\n");
      out.write("\r\n");
      out.write("		error: function(err) {\r\n");
      out.write("			console.log(err);\r\n");
      out.write("		\r\n");
      out.write("		} \r\n");
      out.write("	});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$('#myOrderView1 #orderCancleBtn').click(function(){\r\n");
      out.write("	location.href='/milkyWayForest/mypage/myOrderCancel?paymentCode='+$('#paymentCode').val()+'&request=취소';\r\n");
      out.write("});\r\n");
      out.write("$('#myOrderView1 #orderExchangeBtn').click(function(){\r\n");
      out.write("	location.href='/milkyWayForest/mypage/myOrderCancel?paymentCode='+$('#paymentCode').val()+'&request=교환';\r\n");
      out.write("});\r\n");
      out.write("$('#myOrderView1 #orderReturnBtn').click(function(){\r\n");
      out.write("	location.href='/milkyWayForest/mypage/myOrderCancel?paymentCode='+$('#paymentCode').val()+'&request=반품';\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$.fn.colspan = function(rowIdx) {\r\n");
      out.write("	return this.each(function(){\r\n");
      out.write("		\r\n");
      out.write("		var that;\r\n");
      out.write("		$('tr', this).filter(\":eq(\"+rowIdx+\")\").each(function(row) {\r\n");
      out.write("			$(this).find('th').filter(':visible').each(function(col) {\r\n");
      out.write("				if ($(this).html() == $(that).html()) {\r\n");
      out.write("					colspan = $(that).attr(\"colSpan\") || 1;\r\n");
      out.write("					colspan = Number(colspan)+1;\r\n");
      out.write("					\r\n");
      out.write("					$(that).attr(\"colSpan\",colspan);\r\n");
      out.write("					$(this).hide(); // .remove();\r\n");
      out.write("				} else {\r\n");
      out.write("					that = this;\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("				// set the that if not already set\r\n");
      out.write("				that = (that == null) ? this : that;\r\n");
      out.write("				\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("};\r\n");
      out.write("$.fn.rowspan = function(colIdx, isStats) {       \r\n");
      out.write("	return this.each(function(){      \r\n");
      out.write("		var that;     \r\n");
      out.write("		$('tr', this).each(function(row) {      \r\n");
      out.write("			$('td:eq('+colIdx+')', this).filter(':visible').each(function(col) {\r\n");
      out.write("				\r\n");
      out.write("				if ($(this).html() == $(that).html()\r\n");
      out.write("					&& (!isStats \r\n");
      out.write("							|| isStats && $(this).prev().html() == $(that).prev().html()\r\n");
      out.write("							)\r\n");
      out.write("					) {            \r\n");
      out.write("					rowspan = $(that).attr(\"rowspan\") || 1;\r\n");
      out.write("					rowspan = Number(rowspan)+1;\r\n");
      out.write("\r\n");
      out.write("					$(that).attr(\"rowspan\",rowspan);\r\n");
      out.write("					\r\n");
      out.write("					// do your action for the colspan cell here            \r\n");
      out.write("					$(this).hide();\r\n");
      out.write("					\r\n");
      out.write("					//$(this).remove(); \r\n");
      out.write("					// do your action for the old cell here\r\n");
      out.write("					\r\n");
      out.write("				} else {            \r\n");
      out.write("					that = this;         \r\n");
      out.write("				}          \r\n");
      out.write("				\r\n");
      out.write("				// set the that if not already set\r\n");
      out.write("				that = (that == null) ? this : that;      \r\n");
      out.write("			});     \r\n");
      out.write("		});    \r\n");
      out.write("	});  \r\n");
      out.write("}; \r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
