/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-12-13 05:41:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.write;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class memberWrite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/milkyWayForest/bootstrap/css/bootstrap.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/writeAgreeForm.css\">\r\n");
      out.write("<!-- <script type=\"text/javascript\" src=\"/milkyWayForest/js/date.js\"></script> -->\r\n");
      out.write("\r\n");
      out.write("  <form id=\"memberWriteForm\" action=\"/milkyWayForest/write/writeOk\" method=\"post\">\r\n");
      out.write("    <ul id=\"memberWriteBox\">\r\n");
      out.write("      <li id=\"memberWriteLi\">\r\n");
      out.write("        <p id=\"memberWriteTitle\">회원가입</p>\r\n");
      out.write("      </li>\r\n");
      out.write("      <div align=\"center\">\r\n");
      out.write("        <img src=\"https://image.istarbucks.co.kr/common/img/util/mem/icon_find_sally.png\" id=\"image1\">\r\n");
      out.write("      </div>\r\n");
      out.write("      <li id=\"memberWriteContent\">\r\n");
      out.write("          <ul>\r\n");
      out.write("            <li>스타벅스커피에 오신 것을 환영합니다.</li>\r\n");
      out.write("            <li>본인인증 없이 간편하게 가입하실 수 있습니다</li>\r\n");
      out.write("            <li>(만14세 이상 가입 가능)</li>\r\n");
      out.write("          </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li id=\"blankSpace\"></li>\r\n");
      out.write("      <li class=\"blankLi\">\r\n");
      out.write("        <div class=\"labelName\">\r\n");
      out.write("          <p>ID <span>*</span></p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"writeInputText\">\r\n");
      out.write("          <input type=\"text\" id=\"memberWriteId\" name=\"id\" placeholder=\"영문,숫자포함 5~10자\">\r\n");
      out.write("          <input type=\"hidden\" id=\"checkId\" val=\"\">\r\n");
      out.write("          <div id=\"idDiv\" style=\"width:20%; display:inline;\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"blankLi\">\r\n");
      out.write("        <div class=\"labelName\">\r\n");
      out.write("          <p>비밀번호 <span>*</span></p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"writeInputText\">\r\n");
      out.write("          <input type=\"password\" id=\"memberWritePwd\" name=\"pwd\" placeholder=\"영문,숫자,특수문자 포함 8~16자\">\r\n");
      out.write("          <div id=\"pwdDiv\" style=\"width:20%; display:inline;\"></div>\r\n");
      out.write("        </div>  \r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"blankLi\">\r\n");
      out.write("        <div class=\"labelName\">\r\n");
      out.write("          <p>비밀번호 확인 <span>*</span></p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"writeInputText\">\r\n");
      out.write("          <input type=\"password\" id=\"memberWriteRePwd\" placeholder=\"영문,숫자,특수문자 포함 8~16자\">\r\n");
      out.write("          <div id=\"pwdReDiv\" style=\"width:20%; display:inline;\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"blankLi\">\r\n");
      out.write("        <div class=\"labelName\">\r\n");
      out.write("          <p>이름 <span>*</span></p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"writeInputText\">\r\n");
      out.write("          <input type=\"text\" id=\"memberWriteName\" name=\"name\" placeholder=\"한글만 적어주세요\">\r\n");
      out.write("          <div id=\"nameDiv\" style=\"width:20%; display:inline;\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"blankLi\">\r\n");
      out.write("        <div class=\"labelName\">\r\n");
      out.write("          <p>닉네임 <span>*</span></p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"writeInputText\">\r\n");
      out.write("          <input type=\"text\" id=\"memberWriteNick\" name=\"nickname\">\r\n");
      out.write("          <div id=\"nickNameDiv\" style=\"width:20%; display:inline;\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      \r\n");
      out.write("      <li class=\"blankLi\">\r\n");
      out.write("        <div class=\"labelName\">\r\n");
      out.write("          <p>성별 <span>*</span></p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"writeInputText\">\r\n");
      out.write("          <input type=\"radio\" id=\"man\" name=\"gender\" class=\"gender\" value=\"남\">\r\n");
      out.write("          <label for=\"man\" style=\"font-size: 14px; margin-right: 50px;\">남</label>\r\n");
      out.write("          <input type=\"radio\" id=\"woman\" name=\"gender\" class=\"gender\" value=\"여\">\r\n");
      out.write("          <label for=\"woman\" style=\"font-size: 14px;\">여</label>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"blankLi\">\r\n");
      out.write("        <div class=\"labelName\">\r\n");
      out.write("          <p>휴대폰 번호 <span>*</span></p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"writeInputText\">\r\n");
      out.write("          <select id=\"writeTel1\" name=\"tel1\">\r\n");
      out.write("              <option value=\"010\">010</option>\r\n");
      out.write("              <option value=\"011\">011</option>\r\n");
      out.write("              <option value=\"016\">016</option>\r\n");
      out.write("              <option value=\"017\">017</option>\r\n");
      out.write("              <option value=\"018\">018</option>\r\n");
      out.write("              <option value=\"019\">019</option>\r\n");
      out.write("          </select> - \r\n");
      out.write("        <input type=\"text\" id=\"writeTel2\" name=\"tel2\"> - \r\n");
      out.write("        <input type=\"text\" id=\"writeTel3\" name=\"tel3\">\r\n");
      out.write("      </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"blankLi\">\r\n");
      out.write("        <div class=\"labelName\">\r\n");
      out.write("          <p>생년월일 <span>*</span></p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"writeInputText\">\r\n");
      out.write("    		<input type=\"text\" id=\"yy\" name=\"yy\" placeholder=\"ex) 1950\">년\r\n");
      out.write("    		<input type=\"text\" id=\"mm\" name=\"mm\" placeholder= \"ex) 01\">월\r\n");
      out.write("    		<input type=\"text\" id=\"dd\" name=\"dd\" placeholder= \"ex) 01\">일\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"blankLi\">\r\n");
      out.write("        <div class=\"labelName\">\r\n");
      out.write("          <p>아이디 찾기 질문</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"writeInputText\">\r\n");
      out.write("          <select id=\"writeQuestion\" name=\"idPwdQuestion\">\r\n");
      out.write("              <option value=\"false\" align=\"center\">---질문을 선택하세요---</option>\r\n");
      out.write("              <option value=\"추억의 장소\">기억에 남는 추억의 장소는?</option>\r\n");
      out.write("              <option value=\"좌우명\">자신의 인생 좌우명은?</option>\r\n");
      out.write("              <option value=\"보물\">자신의 보물 1호는?</option>\r\n");
      out.write("              <option value=\"선생님\">가장 기억에 남는 선생님 성함은?</option>\r\n");
      out.write("              <option value=\"선물\">받았던 선물 중 기억에 남는 독특한 선물은?</option>\r\n");
      out.write("              <option value=\"친구\">유년시절 가장 생각나는 친구 이름은?</option>\r\n");
      out.write("              <option value=\"책\">인상 깊게 읽은 책 이름은?</option>\r\n");
      out.write("              <option value=\"캐릭터\">내가 좋아하는 캐릭터는?</option>\r\n");
      out.write("          </select>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"blankLi\">\r\n");
      out.write("        <div class=\"labelName\">\r\n");
      out.write("          <p>답</p>\r\n");
      out.write("          </div>\r\n");
      out.write("		  <div class=\"writeInputText\">\r\n");
      out.write("          <input type=\"text\" id=\"writeAnwer\" name=\"idPwdAnswer\" readonly>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"blankLi\">\r\n");
      out.write("        <div class=\"labelName\">\r\n");
      out.write("          <p>가입 경로</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"writeInputText\">\r\n");
      out.write("          <input type=\"text\" id=\"joinPath\" name=\"writePath\">\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"blankLi\">\r\n");
      out.write("        <div class=\"labelName\">\r\n");
      out.write("          <p>이메일 주소 <span>*</span></p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"writeInputText\">\r\n");
      out.write("          	<input type=\"text\" id=\"memberWriteEmail\" name=\"email1\">\r\n");
      out.write("			@\r\n");
      out.write("			<input type=\"text\" id=\"memberWriteEmail1\" name=\"email2\" list=\"email2\" placeholder=\"직접입력\">\r\n");
      out.write("			<datalist id=\"email2\" name=\"email2\">\r\n");
      out.write("				<option value=\"naver.com\">naver.com\r\n");
      out.write("				<option value=\"daum.net\">daum.net\r\n");
      out.write("				<option value=\"gmail.com\">gmail.com\r\n");
      out.write("			</datalist>\r\n");
      out.write("			<input type=\"button\" id=\"athntEmail\" class=\"btn\" value=\"인증메일 전송\">\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"blankLi athntHide\">\r\n");
      out.write("        <div class=\"labelName\">\r\n");
      out.write("          <p>이메일 인증번호<span>*</span></p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div align=\"center\" id=\"athnt\" class=\"writeInputText\">\r\n");
      out.write("      		<input type=\"text\" id=\"athntNmbr\">\r\n");
      out.write("      		<input type=\"button\" id=\"athBtn\" value=\"인증\" class=\"btn\"> <div id=\"athDiv\" style=\"width:20%; display:inline;\"></div>\r\n");
      out.write("      	</div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li style=\"height: 30px;\">\r\n");
      out.write("      	<div>\r\n");
      out.write("			<div id=\"emailDiv\"></div>   	\r\n");
      out.write("       	</div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li style=\"height:80px;\">\r\n");
      out.write("        <div align=\"center\">\r\n");
      out.write("          <input type=\"button\" id=\"memberWriteBtn\" class=\"btn\" value=\"회원가입\">\r\n");
      out.write("          <input type=\"reset\" id=\"memberWriteReset\" class=\"btn\" value=\"취소\">\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("  </form>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/milkyWayForest/js/write.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
