/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-12-15 00:58:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class body_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1639138034579L));
    _jspx_dependants.put("jar:file:/D:/Spring/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/milkyWayForest/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write("<html>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/milkyWayForest/css/thirdScroll.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/milkyWayForest/css/jquery.fullPage.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/milkyWayForest/css/body.css\"><!-- pc버전 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/milkyWayForest/css/body_tablet.css\" media=\"all and (max-width:1252px)\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/milkyWayForest/css/body_mobile.css\" media=\"all and (max-width:767px)\"> <!--960 이하 모바일-->	\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".section {  width:100%; height:100%; position:relative; color:#ffffff; font-size:24pt; }\r\n");
      out.write(".section .second_section_text { position:relative; top:26%; transform:translate(-47%, -50%); opacity:0;}  \r\n");
      out.write(".fp-completely .second_section_text, .fp-completely .text_container { animation:fade_in .5s  0s forwards;  }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("@keyframes fade_in {\r\n");
      out.write("	0% { opacity:0; left:40%;}\r\n");
      out.write("	100% { opacity:1; left:50%;} \r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- 전체영역 -->\r\n");
      out.write("<div id=\"fullPage\">\r\n");
      out.write("\r\n");
      out.write("	<!-- FullPage -->\r\n");
      out.write("	<div id=\"fullpage\">\r\n");
      out.write("		<section class=\"section\" style=\"background-attachment: fixed;\">\r\n");
      out.write("			<div class=\"sildeDiv\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li>\r\n");
      out.write("						<img src=\"/milkyWayForest/image/main1_Image.jpg\" alt=\"mainpic1.jpg\" id=\"image1\">\r\n");
      out.write("					</li>\r\n");
      out.write("					<li>\r\n");
      out.write("						<img src=\"/milkyWayForest/image/mainImage3.jpg\" alt=\"mainImage3.jpg\" id=\"image2\">\r\n");
      out.write("					</li>\r\n");
      out.write("					<li>\r\n");
      out.write("						<img src=\"/milkyWayForest/image/imageSlide.jpg\" alt=\"imageSlide.jpg\" id=\"image3\">\r\n");
      out.write("					</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("				<div id=\"dotDiv\" style=\"text-align:center\">\r\n");
      out.write("					<span class=\"dotSpan\"></span> \r\n");
      out.write("					<span class=\"dotSpan\"></span> \r\n");
      out.write("					<span class=\"dotSpan\"></span> \r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		\r\n");
      out.write("			<!-- <div class=\"slide\">\r\n");
      out.write("				<img src=\"/milkyWayForest/image/main1_Image.jpg\" alt=\"mainpic1.jpg\" \r\n");
      out.write("				style=\"width: 110vw; height: 100vh;  top: 0;\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"slide\">\r\n");
      out.write("				<img src=\"/milkyWayForest/image/mainImage3.jpg\" alt=\"mainImage3.jpg\" \r\n");
      out.write("				style=\"width: 100vw; height: 100vh;  top: 0;\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"slide\">\r\n");
      out.write("				<img src=\"/milkyWayForest/image/imageSlide.jpg\" alt=\"imageSlide.jpg\" \r\n");
      out.write("				style=\"width: 100%; height: 100%;  top: 0;\">\r\n");
      out.write("			</div> -->\r\n");
      out.write("		</section>\r\n");
      out.write("		\r\n");
      out.write("		<section class=\"section\">\r\n");
      out.write("			<div class=\"second_section_text\">\r\n");
      out.write("				<h1>Pick Your Favorite</h1>\r\n");
      out.write("	\r\n");
      out.write("				<h2 style=\"white-space:pre-line;\">\r\n");
      out.write("				다양한 메뉴를 은하숲에서 즐겨보세요<br>\r\n");
      out.write("	         	은하숲만의 특별함을 경험할수 있는 최상의 음료<br>\r\n");
      out.write("	          	은하숲 커피와 완벽한 어울림을 자랑하는 푸드<br>\r\n");
      out.write("	         	다양한 시도와 디자인으로 가치를 더하는 상품<br>\r\n");
      out.write("	         	소중한 사람에게 은하숲 상품들로 마음을 전하세요<br>\r\n");
      out.write("         		</h2>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("		\r\n");
      out.write("		<section class=\"section\">\r\n");
      out.write("			<div class=\"Allcontainer\">\r\n");
      out.write("				<div class=\"text_container\">\r\n");
      out.write("					<h1>은하숲을 가까이에서 경험해보세요</h1>\r\n");
      out.write("		\r\n");
      out.write("					<h3>고객님과 가장 가까이 있는 매장을 찾아보세요!</h3>\r\n");
      out.write("	         		\r\n");
      out.write("	         		<h4 style=\"white-space:pre-line;\">\r\n");
      out.write("	         		차별화된 커피 경험을 누릴 수 있는 <strong>은하숲</strong><br>\r\n");
      out.write("		         	다양한 방법으로 편리하게 즐길 수 있는 <strong>은하숲</strong><br>\r\n");
      out.write("		          	함께해서 더 따뜻할 수 있는 지역사회 소통 공간 <strong>은하숲</strong><br>\r\n");
      out.write("	         		</h4>\r\n");
      out.write("				</div>\r\n");
      out.write("			         		\r\n");
      out.write("				<div class=\"container2\">\r\n");
      out.write("				  <div class=\"row beans\">\r\n");
      out.write("				  </div>\r\n");
      out.write("				  <div class=\"row grinder\">\r\n");
      out.write("				  </div>\r\n");
      out.write("				  <div class=\"row grinder_bottom\">\r\n");
      out.write("				  </div>\r\n");
      out.write("				  <div class=\"row v60\">\r\n");
      out.write("				  </div>\r\n");
      out.write("				  <div class=\"row drip\">\r\n");
      out.write("				  </div>\r\n");
      out.write("				  <div class=\"row cup\">\r\n");
      out.write("				  </div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("		\r\n");
      out.write("		<section class=\"section fp-auto-height\">\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/main/footer.jsp", out, false);
      out.write("\r\n");
      out.write("		</section>\r\n");
      out.write("	</div>	\r\n");
      out.write("</div>\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<script src=\"/milkyWayForest/js/jquery.fullPage.js\"></script>\r\n");
      out.write("<script src=\"/milkyWayForest/js/body.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
